/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatDevBranchingUiPrototypesRouteImport } from './routes/_chat.dev.branching-ui-prototypes'
import { Route as ChatDevArchiveUiExampleRouteImport } from './routes/_chat.dev.archive-ui-example'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDevBranchingUiPrototypesRoute =
  ChatDevBranchingUiPrototypesRouteImport.update({
    id: '/dev/branching-ui-prototypes',
    path: '/dev/branching-ui-prototypes',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatDevArchiveUiExampleRoute = ChatDevArchiveUiExampleRouteImport.update({
  id: '/dev/archive-ui-example',
  path: '/dev/archive-ui-example',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/dev/archive-ui-example': typeof ChatDevArchiveUiExampleRoute
  '/dev/branching-ui-prototypes': typeof ChatDevBranchingUiPrototypesRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/dev/archive-ui-example': typeof ChatDevArchiveUiExampleRoute
  '/dev/branching-ui-prototypes': typeof ChatDevBranchingUiPrototypesRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/dev/archive-ui-example': typeof ChatDevArchiveUiExampleRoute
  '/_chat/dev/branching-ui-prototypes': typeof ChatDevBranchingUiPrototypesRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/models'
    | '/$environmentId/$threadId'
    | '/dev/archive-ui-example'
    | '/dev/branching-ui-prototypes'
    | '/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/models'
    | '/'
    | '/$environmentId/$threadId'
    | '/dev/archive-ui-example'
    | '/dev/branching-ui-prototypes'
    | '/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/models'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/dev/archive-ui-example'
    | '/_chat/dev/branching-ui-prototypes'
    | '/_chat/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/dev/branching-ui-prototypes': {
      id: '/_chat/dev/branching-ui-prototypes'
      path: '/dev/branching-ui-prototypes'
      fullPath: '/dev/branching-ui-prototypes'
      preLoaderRoute: typeof ChatDevBranchingUiPrototypesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/dev/archive-ui-example': {
      id: '/_chat/dev/archive-ui-example'
      path: '/dev/archive-ui-example'
      fullPath: '/dev/archive-ui-example'
      preLoaderRoute: typeof ChatDevArchiveUiExampleRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDevArchiveUiExampleRoute: typeof ChatDevArchiveUiExampleRoute
  ChatDevBranchingUiPrototypesRoute: typeof ChatDevBranchingUiPrototypesRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDevArchiveUiExampleRoute: ChatDevArchiveUiExampleRoute,
  ChatDevBranchingUiPrototypesRoute: ChatDevBranchingUiPrototypesRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsModelsRoute: SettingsModelsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
