/**
 * The session wire contract: schemas, Pi error passthrough, and the command
 * catalog. How a command reaches the real `AgentHarness` lives in `./service`;
 * see `./index` for the module-level story.
 *
 * @module
 */

import type {
  AgentHarnessErrorCode,
  AgentMessage,
  AgentHarnessEvent,
  SessionErrorCode,
  SessionTreeEntry,
} from "@earendil-works/pi-agent-core";
import { AgentHarnessError, SessionError } from "@earendil-works/pi-agent-core";
import type { Effect, Scope, Stream } from "effect";
import { Schema, SchemaGetter } from "effect";
import { Rpc, RpcGroup } from "effect/unstable/rpc";

import { Git } from "../git";
import { Models } from "../models";
import type { ServiceOf } from "../util/rpc";
import { Workspace } from "../workspace";

import { GitActionId } from "./git-actions";

/**
 * Pi's own types, re-exported so consumers can type Pi values without adding a
 * Pi dependency of their own. Core stays the single owner of the Pi version
 * pin, and a pin bump that changes a shape breaks the build at every use site.
 *
 * @category types
 */
export type { AgentHarnessEvent, SessionTreeEntry } from "@earendil-works/pi-agent-core";

/**
 * Identifies one open session.
 *
 * Minted from Pi's own session metadata rather than generated by Honk, so the
 * id a client holds is the id Pi persisted.
 *
 * @category identifiers
 */
export const SessionId = Schema.NonEmptyString.pipe(Schema.brand("SessionId")).annotate({
  identifier: "SessionId",
});
export type SessionId = typeof SessionId.Type;

/**
 * What {@link Create} answers: a session and the workspace it is bound to.
 *
 * Data, not a client-bound handle. It can live in application state, cross a
 * worker boundary, and be rendered by desktop, web, or mobile.
 *
 * @category schemas
 */
export const SessionInfo = Schema.Struct({
  id: SessionId,
  workspaceId: Workspace.WorkspaceId,
}).annotate({
  identifier: "SessionInfo",
});
export type SessionInfo = typeof SessionInfo.Type;

/**
 * No session with this id exists in this host's store.
 *
 * Sessions restore lazily, so "not currently open" is never this error: a
 * persisted session is reopened on first use. What remains is "never
 * existed", plus one honest edge — a session whose workspace is no longer
 * locatable cannot be restored without violating the trust gate, and answers
 * not-found rather than opening an untrusted directory.
 *
 * @category errors
 */
export class NotFoundError extends Schema.TaggedErrorClass<NotFoundError>()(
  "SessionNotFoundError",
  {
    code: Schema.tag("session.not_found"),
    message: Schema.tag("Honk does not know this session."),
    sessionId: Schema.NonEmptyString,
  },
) {}

/**
 * Pi's error code unions, restated as literal lists so the wire schema below
 * is closed. `satisfies` pins each list to Pi's own union: a Pi pin bump that
 * adds or removes a code breaks this file at compile time instead of
 * silently widening the wire contract.
 */
const HARNESS_ERROR_CODES = [
  "busy",
  "invalid_state",
  "invalid_argument",
  "session",
  "hook",
  "auth",
  "compaction",
  "branch_summary",
  "unknown",
] as const satisfies readonly AgentHarnessErrorCode[];

const SESSION_ERROR_CODES = [
  "not_found",
  "invalid_session",
  "invalid_entry",
  "invalid_fork_target",
  "storage",
  "unknown",
] as const satisfies readonly SessionErrorCode[];

/** The serialized form: which Pi class, its stable code, and its message. */
const PiErrorWire = Schema.Union([
  Schema.Struct({
    kind: Schema.tag("harness"),
    code: Schema.Literals(HARNESS_ERROR_CODES),
    message: Schema.String,
  }),
  Schema.Struct({
    kind: Schema.tag("session"),
    code: Schema.Literals(SESSION_ERROR_CODES),
    message: Schema.String,
  }),
]);

/**
 * Pi's own error classes as they cross this boundary.
 *
 * The error a caller receives is a real `AgentHarnessError` or `SessionError`
 * instance — never a Honk lookalike — so `instanceof` and Pi's own `code`
 * unions keep working (spec section 6, invariant 9). In process the instance
 * passes through untouched. Over a serialized transport it encodes to
 * {@link PiErrorWire} and decodes by reconstructing the same Pi class from
 * its stable fields; only the host-side `cause` chain stays behind.
 *
 * @category errors
 */
export const PiError = PiErrorWire.pipe(
  Schema.decodeTo(
    Schema.declare(
      (value): value is AgentHarnessError | SessionError =>
        value instanceof AgentHarnessError || value instanceof SessionError,
      { identifier: "PiError" },
    ),
    {
      decode: SchemaGetter.transform((wire) =>
        wire.kind === "harness"
          ? new AgentHarnessError(wire.code, wire.message)
          : new SessionError(wire.code, wire.message),
      ),
      encode: SchemaGetter.transform((error) =>
        error instanceof AgentHarnessError
          ? ({ kind: "harness", code: error.code, message: error.message } as const)
          : ({ kind: "session", code: error.code, message: error.message } as const),
      ),
    },
  ),
);
export type PiError = AgentHarnessError | SessionError;

/**
 * Every expected failure reachable through this domain.
 *
 * Includes the workspace refusal because sessions exist only inside trusted
 * workspaces, {@link PiError} because Pi owns run and session failures, the
 * git union because revert restores a checkpoint, and the model resolution
 * union because opening a session — fresh or restored — resolves its model.
 *
 * @category errors
 */
export type Error =
  | NotFoundError
  | Workspace.NotFoundError
  | Git.Error
  | PiError
  | Models.ResolveError;

/**
 * The failures any command that touches a stored session can answer.
 *
 * Sessions restore lazily, so *every* per-session command may be the first
 * touch after a restart — and restoring resolves the transcript's recorded
 * model against the live catalog. A recorded model that left the catalog
 * fails typed here rather than silently substituting another (spec section
 * 11 forbids moving a session between models without consent).
 */
const LookupError = Schema.Union([NotFoundError, PiError, Models.ResolveError]);

/**
 * Creates a session inside a trusted workspace.
 *
 * Sessions exist only inside trusted workspaces. `WorkspaceId`s are minted when
 * trust is recorded, so an unknown id and an untrusted directory are the same
 * refusal — there is no second trust check here, and no way to reach this
 * command without having passed the first one.
 *
 * `model` is the session's own: it is resolved against the live catalog,
 * recorded in the Pi transcript as a `model_change` entry, and restored from
 * there after a restart. Omitted, the session starts on the first model of the
 * first configured provider — a client that cares which model runs passes the
 * reference (spec section 11).
 *
 * @category commands
 */
export const Create = Rpc.make("session.create", {
  payload: {
    workspaceId: Workspace.WorkspaceId,
    model: Schema.optionalKey(Models.ModelRef),
  },
  success: SessionInfo,
  error: Schema.Union([Workspace.NotFoundError, Models.ResolveError, PiError]),
});

/**
 * Sends a prompt and settles at Pi's prompt settlement point.
 *
 * Success stays `void` on purpose. The assistant message lands in the Pi
 * session, and the client reads it through {@link Reload} — returning it here
 * would create a second path to the same content that could disagree with the
 * transcript.
 *
 * TODO(core-migration §6): returning the committed message over a transport
 * waits for Pi to export its `AssistantMessage` runtime schema.
 *
 * @category commands
 */
export const Prompt = Rpc.make("session.prompt", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Pi values passing through the wire under Pi's TypeScript types alone.
 *
 * Spec section 13 permits this only for a boundary inside one installed
 * artifact: the desktop main process and its renderer ship from one lockfile,
 * so no version skew can exist between them, and a Pi pin bump that changes a
 * shape breaks the build at every use site.
 *
 * TODO(core-migration §6, §13): these casts are the blocker for any genuinely
 * remote or version-skewed client, and they violate the section 14 ban on
 * type assertions. They cannot be replaced by `@honk/pi-protocol` alone: that
 * package vendors Pi's *protocol* schemas (`TranscriptItem`,
 * `SessionSnapshot`), which are projections produced by Pi's `pi-server` —
 * not schemas for raw `SessionTreeEntry`/`AgentHarnessEvent` values. Closing
 * this needs Honk to adopt the projections too (changing `ReloadOutput` to
 * carry `TranscriptItem`s), or Pi to publish runtime schemas for the raw
 * values. Either way, a hand-written Honk mirror schema stays forbidden.
 */
const PiMessage = Schema.Unknown as unknown as Schema.Codec<AgentMessage>;
const PiEntry = Schema.Unknown as unknown as Schema.Codec<SessionTreeEntry>;
const PiEvent = Schema.Unknown as unknown as Schema.Codec<AgentHarnessEvent>;

/**
 * What {@link Abort} hands back: the queued messages Pi cleared.
 *
 * Stopping must never destroy something the user typed (spec/conversation.md
 * section 7): the composer restores this text to the editor.
 *
 * @category schemas
 */
export const AbortOutput = Schema.Struct({
  clearedSteer: Schema.Array(PiMessage),
  clearedFollowUp: Schema.Array(PiMessage),
}).annotate({ identifier: "SessionAbortOutput" });
export type AbortOutput = typeof AbortOutput.Type;

/**
 * Ends the current run and returns the queued messages it cleared, so a
 * composer can put the user's words back in the editor.
 *
 * @category commands
 */
export const Abort = Rpc.make("session.abort", {
  payload: { sessionId: SessionId },
  success: AbortOutput,
  error: LookupError,
});

/**
 * Runs an agent-driven Git action (spec/conversation.md section 8).
 *
 * One handler appends a `honk.git_action` marker entry and prompts the
 * harness with the core-owned canonical instructions — in that order, so a
 * refused prompt leaves a marker with no turn after it, which *is* the
 * failure state and needs no cleanup. Idle-only by construction: a running
 * harness refuses the prompt with Pi's own `busy`.
 *
 * @category commands
 */
export const RunGitAction = Rpc.make("session.run_git_action", {
  payload: {
    sessionId: SessionId,
    action: GitActionId,
    /** Explicit path scope, folded into the instructions when present. */
    files: Schema.optionalKey(Schema.Array(Schema.NonEmptyString)),
  },
  error: LookupError,
});

/**
 * Interjects into the run already in progress.
 *
 * @category commands
 */
export const Steer = Rpc.make("session.steer", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Queues text to send after the current run finishes.
 *
 * Run control mirrors Pi's harness verbs rather than inventing Honk names for
 * them. All three settle through the events stream and the next authoritative
 * read, so their success stays `void`.
 *
 * @category commands
 */
export const FollowUp = Rpc.make("session.follow_up", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Whether the harness is working right now.
 *
 * Enough for a client to show that work is active. It is not a Honk copy of
 * Pi's lifecycle: anything richer belongs to Pi's events and its session data.
 *
 * @category schemas
 */
export const RunStatus = Schema.Literals(["idle", "running"]).annotate({
  identifier: "RunStatus",
});
export type RunStatus = typeof RunStatus.Type;

/**
 * One authoritative read: committed Pi entries plus enough status to show
 * whether work is active.
 *
 * Committed data only. Partial token updates are never persisted or
 * reconstructed here — while a run is active the client renders the committed
 * transcript and its own pending-status affordance, and the complete assistant
 * message appears when Pi commits it.
 *
 * @category schemas
 */
export const ReloadOutput = Schema.Struct({
  entries: Schema.Array(PiEntry),
  status: RunStatus,
}).annotate({ identifier: "ReloadOutput" });
export type ReloadOutput = typeof ReloadOutput.Type;

/**
 * Reads the session authoritatively.
 *
 * Idempotent and side-effect free. It never acquires the session, restarts the
 * harness, or changes its lifetime, so three clients may call it independently
 * and concurrently with a running prompt. This is the repair mechanism for
 * every dropped event and every reconnect.
 *
 * @category commands
 */
export const Reload = Rpc.make("session.reload", {
  payload: { sessionId: SessionId },
  success: ReloadOutput,
  error: LookupError,
});

/**
 * What one settled turn did to the workspace.
 *
 * `entryId` is the Pi entry whose settlement captured the turn's checkpoint —
 * the last entry of that turn — so a client can attach the change receipt to
 * its transcript row and hand the id back to {@link Revert}. Files reuse
 * `sdk.git`'s change shape, so one review component renders a turn diff and a
 * working-tree diff alike.
 *
 * @category schemas
 */
export const TurnChanges = Schema.Struct({
  entryId: Schema.NonEmptyString,
  files: Schema.Array(Git.FileChange),
}).annotate({ identifier: "SessionTurnChanges" });
export type TurnChanges = typeof TurnChanges.Type;

/**
 * @category schemas
 */
export const ChangesOutput = Schema.Struct({
  turns: Schema.Array(TurnChanges),
}).annotate({ identifier: "SessionChangesOutput" });
export type ChangesOutput = typeof ChangesOutput.Type;

/**
 * What did *this* conversation change, turn by turn?
 *
 * A workspace answers "what changed here"; a thread must answer "what did this
 * conversation change", and those differ the moment two sessions share a
 * directory. `changes` is the second question, at turn granularity.
 *
 * Each settled turn captured a workspace checkpoint, and a turn's changes are
 * the diff between its checkpoint and the one before it — so shell writes and
 * generated files appear, not just tool-declared edits. The tool calls of the
 * turn act as an attribution gate over that diff: a turn that used only
 * declaring tools claims only the paths it named, which is what keeps a
 * sibling session's edits (or the user's own) out of this turn's receipt. A
 * turn that ran an opaque mutator — shell, an MCP tool — claims the whole
 * diff, because filtering it would silently hide real writes.
 *
 * It stores nothing beyond the checkpoints themselves: the answer is
 * recomputed from the git object store and the committed transcript. A
 * workspace without a repository has no checkpoints and honestly reports no
 * turns.
 *
 * Content diffs are not here. `changes` answers *which* paths per turn;
 * `sdk.git.checkpointDiff` answers *what* changed in them.
 *
 * @example
 * ```ts
 * const { turns } = await sdk.session.changes({ sessionId });
 * for (const turn of turns) {
 *   renderReceipt(turn.entryId, turn.files);
 * }
 * ```
 *
 * @category commands
 */
export const Changes = Rpc.make("session.changes", {
  payload: { sessionId: SessionId },
  success: ChangesOutput,
  error: LookupError,
});

/**
 * Moves the session to another trusted workspace — `/cd`.
 *
 * Holding a `WorkspaceId` proves a trust decision was made, so there is no
 * second permission gate here: an unknown id and an untrusted directory are
 * the same refusal. The move takes effect at the next turn — Pi resolves the
 * harness tool context per turn snapshot, so a run already in progress
 * finishes in the directory it started in.
 *
 * The move is recorded in the Pi transcript as a custom entry (out of model
 * context, like Pi's own model-change entries), and a fresh checkpoint is
 * captured in the new workspace so the next turn's changes diff against the
 * directory as the session found it.
 *
 * @category commands
 */
export const SetWorkspace = Rpc.make("session.set_workspace", {
  payload: { sessionId: SessionId, workspaceId: Workspace.WorkspaceId },
  error: Schema.Union([LookupError, Workspace.NotFoundError]),
});

/**
 * Rewrites the workspace to the checkpoint a turn captured.
 *
 * `entryId` names a turn from {@link Changes}, or `"base"` for the state the
 * session found the workspace in. The revert is recorded in the transcript as
 * a custom entry, and a safety checkpoint of the present is captured under
 * that entry first — so a revert is itself revertible, and the undo is a
 * revert to the entry the revert created.
 *
 * Destructive for the working tree, never for the transcript: the
 * conversation keeps every turn, and only the files move. The client decides
 * whether to also steer the conversation.
 *
 * @category commands
 */
export const Revert = Rpc.make("session.revert", {
  payload: { sessionId: SessionId, entryId: Schema.NonEmptyString },
  error: Schema.Union([LookupError, Git.Failure]),
});

/**
 * One stored session as a list renders it.
 *
 * `directory` is the workspace the session was created in — the stable
 * grouping for a home screen. A session that later `/cd`'d elsewhere still
 * lists under its origin; the current binding is runtime state and belongs to
 * the opened session.
 *
 * @category schemas
 */
export const SessionSummary = Schema.Struct({
  id: SessionId,
  workspaceId: Workspace.WorkspaceId,
  directory: Schema.NonEmptyString,
  /** Pi's creation timestamp, verbatim — what a home screen sorts by. */
  createdAt: Schema.String,
}).annotate({ identifier: "SessionSummary" });
export type SessionSummary = typeof SessionSummary.Type;

/**
 * @category schemas
 */
export const ListOutput = Schema.Struct({
  sessions: Schema.Array(SessionSummary),
}).annotate({ identifier: "SessionListOutput" });
export type ListOutput = typeof ListOutput.Type;

/**
 * Lists every stored session this host can still place.
 *
 * A metadata read, never a restore: no harness opens because a list was
 * rendered. A session whose directory is no longer locatable in the trust
 * store is omitted — surfacing it would invite an open the trust gate must
 * refuse.
 *
 * @category commands
 */
export const List = Rpc.make("session.list", {
  payload: {},
  success: ListOutput,
  error: PiError,
});

/**
 * Resolves one session by id without opening it.
 *
 * @category commands
 */
export const Get = Rpc.make("session.get", {
  payload: { sessionId: SessionId },
  success: SessionInfo,
  error: Schema.Union([NotFoundError, PiError]),
});

/**
 * Deletes one session's transcript from the store, and its checkpoints with
 * it.
 *
 * An open session is aborted and evicted first, so a run cannot keep writing
 * to a transcript that no longer exists. The session's checkpoint refs are
 * pruned from every repository its snapshots touched — snapshots of turns
 * nobody can name anymore are not history, they are litter. Pruning is
 * best-effort: a workspace that left the trust store is unreachable, and
 * deletion proceeds without it.
 *
 * @category commands
 */
export const Delete = Rpc.make("session.delete", {
  payload: { sessionId: SessionId },
  error: Schema.Union([NotFoundError, PiError]),
});

/**
 * One element of the {@link Events} stream.
 *
 * The `live` head frame is Honk-owned protocol, and the only piece of this
 * module that is not a Pi value. The server sends it once its subscription is
 * live, which is the wire version of the deterministic "start listening, then
 * read" handoff. An in-process caller can observe that moment as an Effect
 * resolving; a remote client can only observe it as data.
 *
 * Everything after it is a Pi `AgentHarnessEvent`, carried unchanged.
 *
 * @category schemas
 */
export const EventsFrame = Schema.Union([
  Schema.Struct({ type: Schema.Literal("live") }),
  Schema.Struct({ type: Schema.Literal("event"), event: PiEvent }),
]).annotate({ identifier: "EventsFrame" });
export type EventsFrame = typeof EventsFrame.Type;

/**
 * Subscribes to live harness events for one session.
 *
 * Advisory by design. Ending the stream detaches this client without touching
 * the run, and a client that misses events repairs itself with {@link Reload}
 * rather than asking for replay.
 *
 * @category commands
 */
export const Events = Rpc.make("session.events", {
  payload: { sessionId: SessionId },
  success: EventsFrame,
  error: LookupError,
  stream: true,
});

/**
 * The request/response command catalog, declared once.
 *
 * Everything else derives from this record: the {@link Rpcs} group, the
 * service {@link Interface}, and the client namespace in `honk-core`.
 * {@link Events} stays outside it because a stream command is not a
 * request/response method; it is added to the group and to the interface by
 * hand below.
 *
 * TODO(core-migration §4): session branch and tree navigation, compaction,
 * model change, and thinking-level change are all Pi harness operations with
 * no command here yet.
 *
 * @category commands
 */
export const commands = {
  create: Create,
  prompt: Prompt,
  abort: Abort,
  steer: Steer,
  followUp: FollowUp,
  runGitAction: RunGitAction,
  reload: Reload,
  changes: Changes,
  setWorkspace: SetWorkspace,
  revert: Revert,
  list: List,
  get: Get,
  delete: Delete,
};

/**
 * The session command group, derived from {@link commands} plus the
 * {@link Events} stream.
 *
 * @category commands
 */
export class Rpcs extends RpcGroup.make(...Object.values(commands), Events) {}

/**
 * The session service as in-process callers use it.
 *
 * The request/response methods derive from {@link commands}, so the service
 * cannot drift from the wire contract. {@link Interface.events} is declared by
 * hand because its in-process shape — an Effect resolving to a Stream — is
 * richer than the wire's frame stream.
 *
 * @category service
 */
export interface Interface extends ServiceOf<typeof commands> {
  /**
   * Subscribes to this session's events.
   *
   * Two-stage on purpose. The outer Effect resolves only *after* the
   * subscription is live, which is what makes "start listening, then reload"
   * deterministic: every event published after it completes reaches the
   * returned stream. A single-stage API that returned a lazy stream could not
   * express that guarantee, because the caller would not know when listening
   * began.
   *
   * The `Scope` owns the subscription. Closing it detaches the client without
   * touching the run.
   */
  readonly events: (input: {
    readonly sessionId: SessionId;
  }) => Effect.Effect<
    Stream.Stream<AgentHarnessEvent>,
    NotFoundError | PiError | Models.ResolveError,
    Scope.Scope
  >;
}
