/**
 * Sessions: the commands that drive a real Pi `AgentHarness`.
 *
 * Pi has a persisted `Session` and a live `AgentHarness`. The Pi session stores
 * entries, branches, model changes, thinking-level changes, and active-tool
 * changes; the harness is the in-memory object that operates on it. This module
 * keeps the two together while a session is open and exposes commands that call
 * the real harness.
 *
 * Honk does not define a second session schema, message model, or event union.
 * Values that cross this boundary are Pi's own, and the durable truth is always
 * the Pi session — never a Honk copy of it.
 *
 * The read model has two channels, and the asymmetry is deliberate:
 *
 * - {@link Reload} is authoritative. It is an idempotent committed read that
 *   works whether the harness is idle or running and does not depend on which
 *   clients are attached.
 * - {@link Events} is advisory. Events are temporary notifications that let an
 *   attached interface update without reloading after every change. A missed
 *   event is repaired by the next reload, so nothing durable depends on them.
 *
 * @example
 * ```ts
 * // Start listening, then read: the `live` head frame makes the handoff
 * // deterministic, so no event can slip between subscribe and reload.
 * for await (const frame of sdk.session.events({ sessionId })) {
 *   if (frame.type === "live") {
 *     render((await sdk.session.reload({ sessionId })).entries);
 *   } else {
 *     applyEvent(frame.event);
 *   }
 * }
 * ```
 *
 * @see spec/core.md sections 4 and 9, and invariants 2 through 5.
 * @module
 */

import type {
  AgentHarnessErrorCode,
  AgentHarnessEvent,
  AgentHarnessOptions,
  Session as PiSession,
  SessionErrorCode,
  SessionTreeEntry,
} from "@earendil-works/pi-agent-core";
import {
  AgentHarness,
  AgentHarnessError,
  JsonlSessionRepo,
  SessionError,
} from "@earendil-works/pi-agent-core";
import type { Models as PiModels } from "@earendil-works/pi-ai";
import type { Scope } from "effect";
import { Context, Effect, Layer, PubSub, Ref, Schema, SchemaGetter, Stream } from "effect";
import { Rpc, RpcGroup } from "effect/unstable/rpc";

import { Git } from "./git";
import { Models } from "./models";
import { Tools } from "./tools";
import type { Method } from "./util/rpc";
import { Workspace } from "./workspace";

/**
 * Pi's own types, re-exported so consumers can type Pi values without adding a
 * Pi dependency of their own. Core stays the single owner of the Pi version
 * pin, and a pin bump that changes a shape breaks the build at every use site.
 *
 * @category types
 */
export type { AgentHarnessEvent, SessionTreeEntry } from "@earendil-works/pi-agent-core";

/**
 * Identifies one open session.
 *
 * Minted from Pi's own session metadata rather than generated by Honk, so the
 * id a client holds is the id Pi persisted.
 *
 * @category identifiers
 */
export const SessionId = Schema.NonEmptyString.pipe(Schema.brand("SessionId")).annotate({
  identifier: "SessionId",
});
export type SessionId = typeof SessionId.Type;

/**
 * What {@link Create} answers: a session and the workspace it is bound to.
 *
 * Data, not a client-bound handle. It can live in application state, cross a
 * worker boundary, and be rendered by desktop, web, or mobile.
 *
 * @category schemas
 */
export const SessionInfo = Schema.Struct({
  id: SessionId,
  workspaceId: Workspace.WorkspaceId,
}).annotate({
  identifier: "SessionInfo",
});
export type SessionInfo = typeof SessionInfo.Type;

/**
 * No session with this id exists in this host's store.
 *
 * Sessions restore lazily, so "not currently open" is never this error: a
 * persisted session is reopened on first use. What remains is "never
 * existed", plus one honest edge — a session whose workspace is no longer
 * locatable cannot be restored without violating the trust gate, and answers
 * not-found rather than opening an untrusted directory.
 *
 * @category errors
 */
export class NotFoundError extends Schema.TaggedErrorClass<NotFoundError>()(
  "SessionNotFoundError",
  {
    code: Schema.tag("session.not_found"),
    message: Schema.tag("Honk does not know this session."),
    sessionId: Schema.NonEmptyString,
  },
) {}

/**
 * Pi's error code unions, restated as literal lists so the wire schema below
 * is closed. `satisfies` pins each list to Pi's own union: a Pi pin bump that
 * adds or removes a code breaks this file at compile time instead of
 * silently widening the wire contract.
 */
const HARNESS_ERROR_CODES = [
  "busy",
  "invalid_state",
  "invalid_argument",
  "session",
  "hook",
  "auth",
  "compaction",
  "branch_summary",
  "unknown",
] as const satisfies readonly AgentHarnessErrorCode[];

const SESSION_ERROR_CODES = [
  "not_found",
  "invalid_session",
  "invalid_entry",
  "invalid_fork_target",
  "storage",
  "unknown",
] as const satisfies readonly SessionErrorCode[];

/** The serialized form: which Pi class, its stable code, and its message. */
const PiErrorWire = Schema.Union([
  Schema.Struct({
    kind: Schema.tag("harness"),
    code: Schema.Literals(HARNESS_ERROR_CODES),
    message: Schema.String,
  }),
  Schema.Struct({
    kind: Schema.tag("session"),
    code: Schema.Literals(SESSION_ERROR_CODES),
    message: Schema.String,
  }),
]);

/**
 * Pi's own error classes as they cross this boundary.
 *
 * The error a caller receives is a real `AgentHarnessError` or `SessionError`
 * instance — never a Honk lookalike — so `instanceof` and Pi's own `code`
 * unions keep working (spec section 6, invariant 9). In process the instance
 * passes through untouched. Over a serialized transport it encodes to
 * {@link PiErrorWire} and decodes by reconstructing the same Pi class from
 * its stable fields; only the host-side `cause` chain stays behind.
 *
 * @category errors
 */
export const PiError = PiErrorWire.pipe(
  Schema.decodeTo(
    Schema.declare(
      (value): value is AgentHarnessError | SessionError =>
        value instanceof AgentHarnessError || value instanceof SessionError,
      { identifier: "PiError" },
    ),
    {
      decode: SchemaGetter.transform((wire) =>
        wire.kind === "harness"
          ? new AgentHarnessError(wire.code, wire.message)
          : new SessionError(wire.code, wire.message),
      ),
      encode: SchemaGetter.transform((error) =>
        error instanceof AgentHarnessError
          ? ({ kind: "harness", code: error.code, message: error.message } as const)
          : ({ kind: "session", code: error.code, message: error.message } as const),
      ),
    },
  ),
);
export type PiError = AgentHarnessError | SessionError;

/**
 * Every expected failure reachable through this domain.
 *
 * Includes the workspace refusal because sessions exist only inside trusted
 * workspaces, {@link PiError} because Pi owns run and session failures, the
 * git union because revert restores a checkpoint, and the model resolution
 * union because opening a session — fresh or restored — resolves its model.
 *
 * @category errors
 */
export type Error =
  | NotFoundError
  | Workspace.NotFoundError
  | Git.Error
  | PiError
  | Models.ResolveError;

/**
 * The failures any command that touches a stored session can answer.
 *
 * Sessions restore lazily, so *every* per-session command may be the first
 * touch after a restart — and restoring resolves the transcript's recorded
 * model against the live catalog. A recorded model that left the catalog
 * fails typed here rather than silently substituting another (spec section
 * 11 forbids moving a session between models without consent).
 */
const LookupError = Schema.Union([NotFoundError, PiError, Models.ResolveError]);

/**
 * Runs one Pi operation, keeping Pi's typed failures and Pi's crashes apart.
 *
 * A rejection that is a Pi error class is an expected outcome — a busy
 * harness, steering while idle, a broken session read — and lands on the
 * error channel as itself. Anything else is a bug and stays a defect.
 *
 * Interruption is deliberately not wired to `harness.abort()`: a run belongs
 * to the session, not to the caller that happened to await it, and a client
 * that disconnects mid-prompt must never end work in progress (spec section
 * 10). Ending a run is its own command.
 */
const runPi = <A>(run: () => Promise<A>): Effect.Effect<A, PiError> =>
  Effect.tryPromise({ try: run, catch: (cause) => cause }).pipe(
    Effect.catch((cause) =>
      cause instanceof AgentHarnessError || cause instanceof SessionError
        ? Effect.fail(cause)
        : Effect.die(cause),
    ),
  );

/**
 * Creates a session inside a trusted workspace.
 *
 * Sessions exist only inside trusted workspaces. `WorkspaceId`s are minted when
 * trust is recorded, so an unknown id and an untrusted directory are the same
 * refusal — there is no second trust check here, and no way to reach this
 * command without having passed the first one.
 *
 * `model` is the session's own: it is resolved against the live catalog,
 * recorded in the Pi transcript as a `model_change` entry, and restored from
 * there after a restart. Omitted, the session starts on the first model of the
 * first configured provider — a client that cares which model runs passes the
 * reference (spec section 11).
 *
 * @category commands
 */
export const Create = Rpc.make("session.create", {
  payload: {
    workspaceId: Workspace.WorkspaceId,
    model: Schema.optionalKey(Models.ModelRef),
  },
  success: SessionInfo,
  error: Schema.Union([Workspace.NotFoundError, Models.ResolveError, PiError]),
});

/**
 * Sends a prompt and settles at Pi's prompt settlement point.
 *
 * Success stays `void` on purpose. The assistant message lands in the Pi
 * session, and the client reads it through {@link Reload} — returning it here
 * would create a second path to the same content that could disagree with the
 * transcript.
 *
 * TODO(core-migration §6): returning the committed message over a transport
 * waits for Pi to export its `AssistantMessage` runtime schema.
 *
 * @category commands
 */
export const Prompt = Rpc.make("session.prompt", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Ends the current run and clears pending queues.
 *
 * @category commands
 */
export const Abort = Rpc.make("session.abort", {
  payload: { sessionId: SessionId },
  error: LookupError,
});

/**
 * Interjects into the run already in progress.
 *
 * @category commands
 */
export const Steer = Rpc.make("session.steer", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Queues text to send after the current run finishes.
 *
 * Run control mirrors Pi's harness verbs rather than inventing Honk names for
 * them. All three settle through the events stream and the next authoritative
 * read, so their success stays `void`.
 *
 * @category commands
 */
export const FollowUp = Rpc.make("session.follow_up", {
  payload: { sessionId: SessionId, text: Schema.NonEmptyString },
  error: LookupError,
});

/**
 * Whether the harness is working right now.
 *
 * Enough for a client to show that work is active. It is not a Honk copy of
 * Pi's lifecycle: anything richer belongs to Pi's events and its session data.
 *
 * @category schemas
 */
export const RunStatus = Schema.Literals(["idle", "running"]).annotate({
  identifier: "RunStatus",
});
export type RunStatus = typeof RunStatus.Type;

/**
 * Pi values passing through the wire under Pi's TypeScript types alone.
 *
 * Spec section 13 permits this only for a boundary inside one installed
 * artifact: the desktop main process and its renderer ship from one lockfile,
 * so no version skew can exist between them, and a Pi pin bump that changes a
 * shape breaks the build at every use site.
 *
 * TODO(core-migration §6, §13): these two casts are the blocker for any
 * genuinely remote or version-skewed client, and they violate the section 14
 * ban on type assertions. `@honk/pi-protocol` already vendors Pi's TypeBox
 * `TranscriptItem` and `SessionSnapshot` schemas at a pinned upstream ref;
 * `Schema.declare<T>(guard)` over those guards replaces both with real
 * validation and no assertion. A hand-written Honk mirror schema stays
 * forbidden either way.
 */
const PiEntry = Schema.Unknown as unknown as Schema.Codec<SessionTreeEntry>;
const PiEvent = Schema.Unknown as unknown as Schema.Codec<AgentHarnessEvent>;

/**
 * One authoritative read: committed Pi entries plus enough status to show
 * whether work is active.
 *
 * Committed data only. Partial token updates are never persisted or
 * reconstructed here — while a run is active the client renders the committed
 * transcript and its own pending-status affordance, and the complete assistant
 * message appears when Pi commits it.
 *
 * @category schemas
 */
export const ReloadOutput = Schema.Struct({
  entries: Schema.Array(PiEntry),
  status: RunStatus,
}).annotate({ identifier: "ReloadOutput" });
export type ReloadOutput = typeof ReloadOutput.Type;

/**
 * Reads the session authoritatively.
 *
 * Idempotent and side-effect free. It never acquires the session, restarts the
 * harness, or changes its lifetime, so three clients may call it independently
 * and concurrently with a running prompt. This is the repair mechanism for
 * every dropped event and every reconnect.
 *
 * @category commands
 */
export const Reload = Rpc.make("session.reload", {
  payload: { sessionId: SessionId },
  success: ReloadOutput,
  error: LookupError,
});

/**
 * What one settled turn did to the workspace.
 *
 * `entryId` is the Pi entry whose settlement captured the turn's checkpoint —
 * the last entry of that turn — so a client can attach the change receipt to
 * its transcript row and hand the id back to {@link Revert}. Files reuse
 * `sdk.git`'s change shape, so one review component renders a turn diff and a
 * working-tree diff alike.
 *
 * @category schemas
 */
export const TurnChanges = Schema.Struct({
  entryId: Schema.NonEmptyString,
  files: Schema.Array(Git.FileChange),
}).annotate({ identifier: "SessionTurnChanges" });
export type TurnChanges = typeof TurnChanges.Type;

/**
 * @category schemas
 */
export const ChangesOutput = Schema.Struct({
  turns: Schema.Array(TurnChanges),
}).annotate({ identifier: "SessionChangesOutput" });
export type ChangesOutput = typeof ChangesOutput.Type;

/**
 * What did *this* conversation change, turn by turn?
 *
 * A workspace answers "what changed here"; a thread must answer "what did this
 * conversation change", and those differ the moment two sessions share a
 * directory. `changes` is the second question, at turn granularity.
 *
 * Each settled turn captured a workspace checkpoint, and a turn's changes are
 * the diff between its checkpoint and the one before it — so shell writes and
 * generated files appear, not just tool-declared edits. The tool calls of the
 * turn act as an attribution gate over that diff: a turn that used only
 * declaring tools claims only the paths it named, which is what keeps a
 * sibling session's edits (or the user's own) out of this turn's receipt. A
 * turn that ran an opaque mutator — shell, an MCP tool — claims the whole
 * diff, because filtering it would silently hide real writes.
 *
 * It stores nothing beyond the checkpoints themselves: the answer is
 * recomputed from the git object store and the committed transcript. A
 * workspace without a repository has no checkpoints and honestly reports no
 * turns.
 *
 * Content diffs are not here. `changes` answers *which* paths per turn;
 * `sdk.git.checkpointDiff` answers *what* changed in them.
 *
 * @example
 * ```ts
 * const { turns } = await sdk.session.changes({ sessionId });
 * for (const turn of turns) {
 *   renderReceipt(turn.entryId, turn.files);
 * }
 * ```
 *
 * @category commands
 */
export const Changes = Rpc.make("session.changes", {
  payload: { sessionId: SessionId },
  success: ChangesOutput,
  error: LookupError,
});

/**
 * Moves the session to another trusted workspace — `/cd`.
 *
 * Holding a `WorkspaceId` proves a trust decision was made, so there is no
 * second permission gate here: an unknown id and an untrusted directory are
 * the same refusal. The move takes effect at the next turn — Pi resolves the
 * harness tool context per turn snapshot, so a run already in progress
 * finishes in the directory it started in.
 *
 * The move is recorded in the Pi transcript as a custom entry (out of model
 * context, like Pi's own model-change entries), and a fresh checkpoint is
 * captured in the new workspace so the next turn's changes diff against the
 * directory as the session found it.
 *
 * @category commands
 */
export const SetWorkspace = Rpc.make("session.set_workspace", {
  payload: { sessionId: SessionId, workspaceId: Workspace.WorkspaceId },
  error: Schema.Union([LookupError, Workspace.NotFoundError]),
});

/**
 * Rewrites the workspace to the checkpoint a turn captured.
 *
 * `entryId` names a turn from {@link Changes}, or `"base"` for the state the
 * session found the workspace in. The revert is recorded in the transcript as
 * a custom entry, and a safety checkpoint of the present is captured under
 * that entry first — so a revert is itself revertible, and the undo is a
 * revert to the entry the revert created.
 *
 * Destructive for the working tree, never for the transcript: the
 * conversation keeps every turn, and only the files move. The client decides
 * whether to also steer the conversation.
 *
 * @category commands
 */
export const Revert = Rpc.make("session.revert", {
  payload: { sessionId: SessionId, entryId: Schema.NonEmptyString },
  error: Schema.Union([LookupError, Git.Failure]),
});

/**
 * One stored session as a list renders it.
 *
 * `directory` is the workspace the session was created in — the stable
 * grouping for a home screen. A session that later `/cd`'d elsewhere still
 * lists under its origin; the current binding is runtime state and belongs to
 * the opened session.
 *
 * @category schemas
 */
export const SessionSummary = Schema.Struct({
  id: SessionId,
  workspaceId: Workspace.WorkspaceId,
  directory: Schema.NonEmptyString,
  /** Pi's creation timestamp, verbatim — what a home screen sorts by. */
  createdAt: Schema.String,
}).annotate({ identifier: "SessionSummary" });
export type SessionSummary = typeof SessionSummary.Type;

/**
 * @category schemas
 */
export const ListOutput = Schema.Struct({
  sessions: Schema.Array(SessionSummary),
}).annotate({ identifier: "SessionListOutput" });
export type ListOutput = typeof ListOutput.Type;

/**
 * Lists every stored session this host can still place.
 *
 * A metadata read, never a restore: no harness opens because a list was
 * rendered. A session whose directory is no longer locatable in the trust
 * store is omitted — surfacing it would invite an open the trust gate must
 * refuse.
 *
 * @category commands
 */
export const List = Rpc.make("session.list", {
  payload: {},
  success: ListOutput,
  error: PiError,
});

/**
 * Resolves one session by id without opening it.
 *
 * @category commands
 */
export const Get = Rpc.make("session.get", {
  payload: { sessionId: SessionId },
  success: SessionInfo,
  error: Schema.Union([NotFoundError, PiError]),
});

/**
 * Deletes one session's transcript from the store, and its checkpoints with
 * it.
 *
 * An open session is aborted and evicted first, so a run cannot keep writing
 * to a transcript that no longer exists. The session's checkpoint refs are
 * pruned from every repository its snapshots touched — snapshots of turns
 * nobody can name anymore are not history, they are litter. Pruning is
 * best-effort: a workspace that left the trust store is unreachable, and
 * deletion proceeds without it.
 *
 * @category commands
 */
export const Delete = Rpc.make("session.delete", {
  payload: { sessionId: SessionId },
  error: Schema.Union([NotFoundError, PiError]),
});

/**
 * One element of the {@link Events} stream.
 *
 * The `live` head frame is Honk-owned protocol, and the only piece of this
 * module that is not a Pi value. The server sends it once its subscription is
 * live, which is the wire version of the deterministic "start listening, then
 * read" handoff. An in-process caller can observe that moment as an Effect
 * resolving; a remote client can only observe it as data.
 *
 * Everything after it is a Pi `AgentHarnessEvent`, carried unchanged.
 *
 * @category schemas
 */
export const EventsFrame = Schema.Union([
  Schema.Struct({ type: Schema.Literal("live") }),
  Schema.Struct({ type: Schema.Literal("event"), event: PiEvent }),
]).annotate({ identifier: "EventsFrame" });
export type EventsFrame = typeof EventsFrame.Type;

/**
 * Subscribes to live harness events for one session.
 *
 * Advisory by design. Ending the stream detaches this client without touching
 * the run, and a client that misses events repairs itself with {@link Reload}
 * rather than asking for replay.
 *
 * @category commands
 */
export const Events = Rpc.make("session.events", {
  payload: { sessionId: SessionId },
  success: EventsFrame,
  error: LookupError,
  stream: true,
});

/**
 * The session command catalog.
 *
 * TODO(core-migration §4): session listing, retrieval, deletion, branch and
 * tree navigation, compaction, model change, and thinking-level change are all
 * Pi harness operations with no command here yet.
 *
 * @category commands
 */
export class Rpcs extends RpcGroup.make(
  Create,
  Prompt,
  Reload,
  Changes,
  Events,
  Abort,
  Steer,
  FollowUp,
  SetWorkspace,
  Revert,
  List,
  Get,
  Delete,
) {}

/**
 * The session service as in-process callers use it.
 *
 * Every request/response method type derives from its {@link Rpc} through
 * {@link Method}, so the service cannot drift from the wire contract.
 *
 * @category service
 */
export interface Interface {
  readonly create: Method<typeof Create>;
  readonly prompt: Method<typeof Prompt>;
  readonly abort: Method<typeof Abort>;
  readonly steer: Method<typeof Steer>;
  readonly followUp: Method<typeof FollowUp>;
  readonly reload: Method<typeof Reload>;
  readonly changes: Method<typeof Changes>;
  readonly setWorkspace: Method<typeof SetWorkspace>;
  readonly revert: Method<typeof Revert>;
  readonly list: Method<typeof List>;
  readonly get: Method<typeof Get>;
  readonly delete: Method<typeof Delete>;

  /**
   * Subscribes to this session's events.
   *
   * Two-stage on purpose. The outer Effect resolves only *after* the
   * subscription is live, which is what makes "start listening, then reload"
   * deterministic: every event published after it completes reaches the
   * returned stream. A single-stage API that returned a lazy stream could not
   * express that guarantee, because the caller would not know when listening
   * began.
   *
   * The `Scope` owns the subscription. Closing it detaches the client without
   * touching the run.
   */
  readonly events: (input: {
    readonly sessionId: SessionId;
  }) => Effect.Effect<
    Stream.Stream<AgentHarnessEvent>,
    NotFoundError | PiError | Models.ResolveError,
    Scope.Scope
  >;
}

/**
 * @category service
 */
export class Service extends Context.Service<Service, Interface>()("honk/Session") {}

/**
 * What {@link layer} needs beyond its services.
 *
 * The model collection is not here: it lives in {@link Models.Service}, which
 * this layer requires, so the harnesses stream through the same collection
 * the models RPCs describe and credential writes unlock.
 *
 * @category layers
 */
export interface LayerOptions {
  /**
   * The host data directory's environment: Pi session transcripts persist in
   * its `sessions/` subtree through the JSONL repository. The same instance
   * the workspace trust store and lease use.
   */
  readonly storage: Workspace.ExecutionEnv;
}

/**
 * Private host runtime state for one open session.
 *
 * Never serialized and never exposed. Desktop, web, and mobile see commands and
 * Pi values; an `AgentHarness` instance goes only to in-process extensions.
 */
/**
 * Builds the harness for one trusted workspace, with Pi's execution tools
 * bound to that workspace's environment.
 *
 * A top-level helper rather than an inline construction so {@link
 * WorkspaceHarness} can name the resulting type. `AgentHarness` is generic over
 * its tool context and tool union, and both follow from the tools passed here.
 */
const createWorkspaceHarness = (input: {
  readonly session: PiSession;
  readonly models: PiModels;
  readonly model: AgentHarnessOptions["model"];
  readonly binding: SessionBinding;
}) =>
  new AgentHarness({
    session: input.session,
    models: input.models,
    model: input.model,
    tools: [...Tools.builtins()],
    // The provider form of Pi's tool context: resolved at each turn snapshot,
    // so setWorkspace swaps the binding and the next turn runs in the new
    // directory while a run already in progress finishes in its old one.
    toolContext: () => ({ env: input.binding.env }),
  });

/** The harness type Honk actually opens: Pi's, with execution tools bound. */
type WorkspaceHarness = ReturnType<typeof createWorkspaceHarness>;

/**
 * Which workspace the session runs in right now.
 *
 * Mutable because `/cd` is an operation, not a new session: the harness reads
 * it through its tool-context provider, and `sdk.files`/`sdk.git` calls keep
 * addressing workspaces by id regardless.
 */
interface SessionBinding {
  workspace: Workspace.Info;
  env: Workspace.ExecutionEnv;
}

/** One captured checkpoint: which entry settled it, in which workspace's repository. */
interface Snapshot {
  readonly entryId: string;
  readonly workspaceId: Workspace.WorkspaceId;
}

interface OpenSession {
  readonly session: PiSession;
  readonly harness: WorkspaceHarness;
  readonly events: PubSub.PubSub<AgentHarnessEvent>;
  readonly binding: SessionBinding;

  /**
   * The session's checkpoint history, in capture order.
   *
   * Host bookkeeping, not a second transcript: the snapshots themselves live
   * in the workspace repository, and this list only remembers which
   * repository holds each one — which is what lets a session that `/cd`s span
   * two object stores without guessing.
   */
  readonly snapshots: Snapshot[];

  /**
   * Mutated from Pi's plain event callback, where Effect refs are out of
   * reach, and read only by `reload`.
   *
   * TODO(core-migration effect-v4): `SubscriptionRef` models this properly —
   * `getUnsafe` for the Pi callback, an Effect read for `reload`, and
   * `changes` as a stream so status reaches clients without a reload.
   */
  readonly run: { status: RunStatus };
}

/**
 * Builds the session service.
 *
 * Requires {@link Workspace.Service}, {@link Git.Service}, and
 * {@link Models.Service} — each the *same* instance its own RPCs use. A second
 * workspace instance splits the trust store; a second models instance splits
 * the catalog credential writes unlock.
 *
 * @example
 * ```ts
 * const services = Session.layer({ storage }).pipe(
 *   Layer.provide(Models.layer({ collection, credentials })),
 *   Layer.provideMerge(Workspace.defaultLayer({ createExecutionEnv, storage })),
 * );
 * ```
 *
 * @category layers
 */
export const layer = (options: LayerOptions) =>
  Layer.effect(
    Service,
    Effect.gen(function* () {
      const workspaces = yield* Workspace.Service;
      const git = yield* Git.Service;
      const models = yield* Models.Service;

      // One JSONL transcript per session under <dataDirectory>/sessions,
      // owned by Pi's repository for the core's whole lifetime. The durable
      // truth spec section 9 talks about is these files.
      const repo = new JsonlSessionRepo({ fs: options.storage, sessionsRoot: "sessions" });

      // TODO(core-migration §10, effect-v4): sessions are resources, not map
      // entries. Nothing ever calls harness.requestShutdown() or
      // waitForShutdown(), and nothing evicts a closed session, so this map
      // only grows. RcMap with acquireRelease finalizers gives both shutdown
      // and eviction, and replaces this copy-on-write Map in a Ref.
      const open = yield* Ref.make<ReadonlyMap<SessionId, OpenSession>>(new Map());

      /** Reads one session's stored metadata, or nothing if it never existed. */
      const findMetadata = Effect.fnUntraced(function* (sessionId: SessionId) {
        const listed = yield* runPi(() => repo.list());
        return listed.find((metadata) => metadata.id === sessionId);
      });

      /** The transcript record of one /cd: which workspace the session moved to. */
      const WorkspaceChangeData = Schema.Struct({ workspaceId: Workspace.WorkspaceId });

      /**
       * Resolves a `honk.workspace_change` entry to a workspace, or nothing.
       *
       * Nothing when the entry does not decode or the workspace is gone from
       * the trust store — a transcript is history, and history may reference
       * places this host can no longer place.
       */
      const workspaceFromChange = Effect.fnUntraced(function* (data: unknown) {
        const decoded = yield* Schema.decodeUnknownEffect(WorkspaceChangeData)(data).pipe(
          Effect.orElseSucceed(() => undefined),
        );
        if (decoded === undefined) return undefined;
        return yield* workspaces
          .find({ workspaceId: decoded.workspaceId })
          .pipe(Effect.orElseSucceed(() => undefined));
      });

      /**
       * Builds the private runtime state around one Pi session.
       *
       * Shared by create and restore, so a restored session gets exactly the
       * wiring a fresh one does: the harness over the current binding, the
       * event bridge, and the run status.
       */
      const openFromPiSession = Effect.fnUntraced(function* (
        session: PiSession,
        binding: SessionBinding,
        snapshots: Snapshot[],
        model: AgentHarnessOptions["model"],
      ) {
        // TODO(core-migration §7, §12): built-in execution tools only. No
        // resources, no systemPrompt, no MCP or extension tools yet, and no
        // setTools(allTools, activeToolNames) recompute - passing
        // activeToolNames matters there, because Pi retains the previous
        // active names when it is omitted.
        const harness = createWorkspaceHarness({
          session,
          models: models.collection,
          model,
          binding,
        });

        const events = yield* PubSub.unbounded<AgentHarnessEvent>();
        const run: OpenSession["run"] = { status: "idle" };

        // Bridge Pi's callback into the PubSub. Events are temporary
        // notifications: an unbounded pubsub never drops a publish, and
        // subscribers that lag or detach repair themselves with the next
        // authoritative reload.
        harness.subscribe((event) => {
          if (event.type === "agent_start") run.status = "running";
          if (event.type === "settled") run.status = "idle";
          PubSub.publishUnsafe(events, event);
        });

        return { session, harness, events, run, binding, snapshots } satisfies OpenSession;
      });

      /**
       * Walks the transcript's `/cd` records once, answering both questions
       * a stored session poses: which workspace each entry ran in, and where
       * the session ended up.
       */
      const workspaceTrail = Effect.fnUntraced(function* (
        entries: readonly SessionTreeEntry[],
        origin: Workspace.Info,
      ) {
        const attributed: Snapshot[] = [{ entryId: "base", workspaceId: origin.id }];
        let workspace = origin;
        for (const entry of entries) {
          if (entry.type === "custom" && entry.customType === "honk.workspace_change") {
            const target = yield* workspaceFromChange(entry.data);
            if (target) workspace = target;
          }
          attributed.push({ entryId: entry.id, workspaceId: workspace.id });
        }
        return { attributed, workspace };
      });

      /**
       * Restores a stored session into the open map, or reports it
       * unrestorable.
       *
       * Trust gates restoration exactly as it gates creation: the session's
       * directory must still be in the trust store, or no environment is
       * created and the session stays closed. The final workspace binding
       * comes from the transcript's last `/cd` record, so a restored session
       * continues where it moved to, not where it began.
       */
      const restore = Effect.fnUntraced(function* (sessionId: SessionId) {
        const metadata = yield* findMetadata(sessionId);
        if (!metadata) return undefined;
        const origin = yield* workspaces.locate({ directory: metadata.cwd });
        if (!origin) return undefined;

        const session = yield* runPi(() => repo.open(metadata));
        const entries = yield* runPi(() => session.getEntries());
        const { attributed, workspace } = yield* workspaceTrail(entries, origin);

        // The transcript's own model record, resolved against the live
        // catalog. A model that left the catalog fails restoration typed —
        // substituting another would silently move the conversation.
        const model = yield* models.resolve(modelOf(entries));

        // Snapshot history is what actually survives a restart: checkpoint
        // refs in the workspace repositories, intersected with the transcript
        // in transcript order. Nothing is stored twice.
        const captured = new Map<Workspace.WorkspaceId, ReadonlySet<string>>();
        for (const workspaceId of new Set(attributed.map((snapshot) => snapshot.workspaceId))) {
          const names = yield* git
            .checkpoints({ workspaceId, prefix: sessionId })
            .pipe(Effect.orElseSucceed((): Git.CheckpointsOutput => ({ checkpoints: [] })));
          captured.set(
            workspaceId,
            new Set(names.checkpoints.map((name) => name.slice(sessionId.length + 1))),
          );
        }
        const snapshots = attributed.filter(
          (snapshot) => captured.get(snapshot.workspaceId)?.has(snapshot.entryId) ?? false,
        );

        // The id came out of the trust store an instant ago; a miss here is a
        // bug, not an outcome.
        const env = yield* workspaces.env({ workspaceId: workspace.id }).pipe(Effect.orDie);
        const opened = yield* openFromPiSession(session, { workspace, env }, snapshots, model);

        // Two concurrent restores converge on one instance; the loser's
        // harness is dropped unused before it ever ran anything.
        return yield* Ref.modify(open, (map) => {
          const raced = map.get(sessionId);
          if (raced) return [raced, map] as const;
          return [opened, new Map(map).set(sessionId, opened)] as const;
        });
      });

      const lookup = Effect.fnUntraced(function* (sessionId: SessionId) {
        const found = (yield* Ref.get(open)).get(sessionId);
        if (found) return found;
        // Lazy restore: the first use after a restart reopens the session.
        const restored = yield* restore(sessionId);
        if (!restored) return yield* new NotFoundError({ sessionId });
        return restored;
      });

      /**
       * Captures a checkpoint for this session and remembers where it lives.
       *
       * Failures are swallowed on purpose: a workspace without a git
       * repository has no checkpoints, and snapshot bookkeeping must never
       * fail the run that triggered it. A capture that did not happen is
       * simply not recorded, so `changes` stays honest instead of pointing at
       * refs that do not exist.
       */
      const captureSnapshot = Effect.fnUntraced(function* (
        sessionId: SessionId,
        found: OpenSession,
        entryId: string,
      ) {
        const workspaceId = found.binding.workspace.id;
        const captured = yield* git
          .captureCheckpoint({ workspaceId, checkpoint: `${sessionId}/${entryId}` })
          .pipe(
            Effect.as(true),
            Effect.orElseSucceed(() => false),
          );
        if (!captured) return;
        const last = found.snapshots.at(-1);
        if (last !== undefined && last.entryId === entryId && last.workspaceId === workspaceId) {
          return;
        }
        found.snapshots.push({ entryId, workspaceId });
      });

      /** Snapshots the settled state under the turn's last entry id. */
      const settleSnapshot = Effect.fnUntraced(function* (
        sessionId: SessionId,
        found: OpenSession,
      ) {
        const entries = yield* runPi(() => found.session.getEntries());
        yield* captureSnapshot(sessionId, found, entries.at(-1)?.id ?? "base");
      });

      const create = Effect.fn("Session.create")(function* (input: Rpc.Payload<typeof Create>) {
        const workspace = yield* workspaces.find({ workspaceId: input.workspaceId });
        // Resolve the model before anything persists: a reference that fails
        // must not leave an orphan transcript behind.
        const model = yield* models.resolve(input.model);
        // The session's transcript is rooted in its workspace from the first
        // byte: Pi stores the cwd in the session metadata, and that stored
        // directory is what restoration resolves through the trust store.
        const session = yield* runPi(() => repo.create({ cwd: workspace.directory }));
        const metadata = yield* runPi(() => session.getMetadata());
        const id = SessionId.make(metadata.id);

        // The choice is durable from birth: Pi's own model_change entry is
        // what restoration reads, so the session reopens on the model it was
        // created with — even when it was the resolved default.
        yield* runPi(() => session.appendModelChange(model.provider, model.id));

        // One environment per trusted workspace, shared with sdk.files and
        // sdk.git, so all three resolve against the same directory and a
        // caller cannot reach outside it by choosing a different built-in.
        const env = yield* workspaces.env({ workspaceId: workspace.id });
        const opened = yield* openFromPiSession(session, { workspace, env }, [], model);

        // The base checkpoint: the workspace as this session found it, so the
        // first turn has something to diff against and "base" is a revert
        // target meaning "before this conversation touched anything".
        yield* captureSnapshot(id, opened, "base");

        yield* Ref.update(open, (map) => new Map(map).set(id, opened));
        return { id, workspaceId: workspace.id };
      });

      const list = Effect.fn("Session.list")(function* () {
        const listed = yield* runPi(() => repo.list());
        const sessions: SessionSummary[] = [];
        for (const metadata of listed) {
          const located = yield* workspaces.locate({ directory: metadata.cwd });
          // A session whose directory left the trust store is unplaceable:
          // listing it would invite an open the trust gate must refuse.
          if (!located) continue;
          sessions.push({
            id: SessionId.make(metadata.id),
            workspaceId: located.id,
            directory: located.directory,
            createdAt: metadata.createdAt,
          });
        }
        return { sessions } satisfies ListOutput;
      });

      const get = Effect.fn("Session.get")(function* (input: Rpc.Payload<typeof Get>) {
        const opened = (yield* Ref.get(open)).get(input.sessionId);
        if (opened) {
          return {
            id: input.sessionId,
            workspaceId: opened.binding.workspace.id,
          } satisfies SessionInfo;
        }
        // Metadata only — get answers identity, and identity must not cost a
        // harness. The origin workspace is the honest answer for a session
        // nobody has opened; the current binding exists only once it is open.
        const metadata = yield* findMetadata(input.sessionId);
        if (!metadata) return yield* new NotFoundError({ sessionId: input.sessionId });
        const located = yield* workspaces.locate({ directory: metadata.cwd });
        if (!located) return yield* new NotFoundError({ sessionId: input.sessionId });
        return { id: input.sessionId, workspaceId: located.id } satisfies SessionInfo;
      });

      const remove = Effect.fn("Session.delete")(function* (input: Rpc.Payload<typeof Delete>) {
        const metadata = yield* findMetadata(input.sessionId);
        if (!metadata) return yield* new NotFoundError({ sessionId: input.sessionId });
        const opened = (yield* Ref.get(open)).get(input.sessionId);
        if (opened) {
          // End the run before its transcript disappears under it. A failed
          // abort must not block deletion — the user asked for gone.
          yield* runPi(() => opened.harness.abort()).pipe(Effect.ignore);
          yield* Ref.update(open, (map) => {
            const next = new Map(map);
            next.delete(input.sessionId);
            return next;
          });
        }

        // Every repository this session snapshotted into: the live list when
        // the session is open, the transcript's /cd trail when it is not.
        // Best-effort by design — a broken transcript or a vanished workspace
        // must not block the deletion the user asked for.
        const targets = yield* Effect.gen(function* () {
          const ids = new Set<Workspace.WorkspaceId>();
          if (opened) {
            ids.add(opened.binding.workspace.id);
            for (const snapshot of opened.snapshots) ids.add(snapshot.workspaceId);
            return ids;
          }
          const origin = yield* workspaces.locate({ directory: metadata.cwd });
          if (!origin) return ids;
          const session = yield* runPi(() => repo.open(metadata));
          const entries = yield* runPi(() => session.getEntries());
          const { attributed } = yield* workspaceTrail(entries, origin);
          for (const snapshot of attributed) ids.add(snapshot.workspaceId);
          return ids;
        }).pipe(Effect.orElseSucceed(() => new Set<Workspace.WorkspaceId>()));

        yield* Effect.forEach(
          [...targets],
          (workspaceId) =>
            git.deleteCheckpoints({ workspaceId, prefix: input.sessionId }).pipe(Effect.ignore),
          { discard: true },
        );
        yield* runPi(() => repo.delete(metadata));
      });

      const prompt = Effect.fn("Session.prompt")(function* (input: Rpc.Payload<typeof Prompt>) {
        const found = yield* lookup(input.sessionId);
        yield* runPi(() => found.harness.prompt(input.text));
        // Pi's prompt promise resolves at the settlement point, so this is
        // "after the turn": one checkpoint per settled turn, no event-side
        // bookkeeping. Steers and follow-ups fold into the same run and are
        // covered by this capture.
        yield* settleSnapshot(input.sessionId, found);
      });

      const abort = Effect.fn("Session.abort")(function* (input: Rpc.Payload<typeof Abort>) {
        const found = yield* lookup(input.sessionId);
        // The cleared-queue result stays internal; the settled event and the
        // next reload are the client-visible outcome.
        yield* runPi(() => found.harness.abort());
        // An aborted run still wrote whatever it wrote before the abort.
        yield* settleSnapshot(input.sessionId, found);
      });

      const steer = Effect.fn("Session.steer")(function* (input: Rpc.Payload<typeof Steer>) {
        const found = yield* lookup(input.sessionId);
        yield* runPi(() => found.harness.steer(input.text));
      });

      const followUp = Effect.fn("Session.followUp")(function* (
        input: Rpc.Payload<typeof FollowUp>,
      ) {
        const found = yield* lookup(input.sessionId);
        yield* runPi(() => found.harness.followUp(input.text));
      });

      const reload = Effect.fn("Session.reload")(function* (input: {
        readonly sessionId: SessionId;
      }) {
        const found = yield* lookup(input.sessionId);
        // Authoritative committed read straight from the Pi session. It never
        // touches the harness, which is what makes it safe during a run and
        // proves invariant 3: reloading cannot execute work.
        const entries = yield* runPi(() => found.session.getEntries());
        return { entries, status: found.run.status };
      });

      /**
       * Diffs consecutive checkpoints, gated by each turn's own tool calls.
       *
       * The snapshot diff is the truth about content; the turn's tool calls
       * are the truth about attribution. Intersecting them is what keeps a
       * sibling session's edits out of this turn's receipt without hiding
       * what a shell command wrote. A pair whose diff cannot be computed —
       * pruned refs, a repository that went away — contributes nothing rather
       * than failing the read.
       */
      const changes = Effect.fn("Session.changes")(function* (input: {
        readonly sessionId: SessionId;
      }) {
        const found = yield* lookup(input.sessionId);
        const entries = yield* runPi(() => found.session.getEntries());
        const order = new Map(entries.map((entry, index) => [entry.id, index] as const));

        const turns: TurnChanges[] = [];
        for (let index = 1; index < found.snapshots.length; index += 1) {
          const from = found.snapshots[index - 1];
          const to = found.snapshots[index];
          if (from === undefined || to === undefined) continue;
          // A /cd boundary: the two snapshots live in different repositories,
          // so there is no comparable base and the pair is honestly skipped.
          if (from.workspaceId !== to.workspaceId) continue;

          const files = yield* git
            .checkpointChanges({
              workspaceId: to.workspaceId,
              from: `${input.sessionId}/${from.entryId}`,
              to: `${input.sessionId}/${to.entryId}`,
            })
            .pipe(Effect.orElseSucceed((): readonly Git.FileChange[] => []));
          if (files.length === 0) continue;

          const gated = gateTurnFiles(
            files,
            turnToolWrites(entries, order.get(from.entryId), order.get(to.entryId)),
          );
          if (gated.length > 0) turns.push({ entryId: to.entryId, files: gated });
        }
        return { turns } satisfies ChangesOutput;
      });

      const setWorkspace = Effect.fn("Session.setWorkspace")(function* (
        input: Rpc.Payload<typeof SetWorkspace>,
      ) {
        const found = yield* lookup(input.sessionId);
        if (found.binding.workspace.id === input.workspaceId) return;
        const workspace = yield* workspaces.find({ workspaceId: input.workspaceId });
        const env = yield* workspaces.env({ workspaceId: workspace.id });
        found.binding.workspace = workspace;
        found.binding.env = env;

        // The move lands in the Pi transcript as a custom entry — out of
        // model context, like Pi's own model-change entries — and that
        // entry's id names the new workspace's baseline checkpoint, so the
        // next turn diffs against the directory as the session found it.
        const entryId = yield* runPi(() =>
          found.session.appendCustomEntry("honk.workspace_change", {
            workspaceId: workspace.id,
            directory: workspace.directory,
          }),
        );
        yield* captureSnapshot(input.sessionId, found, entryId);
      });

      const revert = Effect.fn("Session.revert")(function* (input: Rpc.Payload<typeof Revert>) {
        const found = yield* lookup(input.sessionId);
        const target = found.snapshots.find((snapshot) => snapshot.entryId === input.entryId);
        if (target === undefined) {
          return yield* new Git.CheckpointNotFoundError({
            checkpoint: `${input.sessionId}/${input.entryId}`,
          });
        }
        // The revert lands in the transcript as a custom entry, and that
        // entry's id names the safety checkpoint of the present. A fresh id
        // by construction: naming the safety by an existing entry would
        // overwrite the very checkpoint being restored. Undo is a revert to
        // this entry.
        const entryId = yield* runPi(() =>
          found.session.appendCustomEntry("honk.revert", { toEntryId: input.entryId }),
        );
        yield* captureSnapshot(input.sessionId, found, entryId);
        yield* git.restoreCheckpoint({
          workspaceId: target.workspaceId,
          checkpoint: `${input.sessionId}/${target.entryId}`,
        });
      });

      const events = Effect.fn("Session.events")(function* (input: {
        readonly sessionId: SessionId;
      }) {
        const found = yield* lookup(input.sessionId);
        // Subscribing before returning is the guarantee: once this effect
        // completes, every subsequent event reaches the caller's stream.
        const subscription = yield* PubSub.subscribe(found.events);
        return Stream.fromSubscription(subscription);
      });

      return Service.of({
        create,
        prompt,
        abort,
        steer,
        followUp,
        reload,
        changes,
        setWorkspace,
        revert,
        list,
        get,
        delete: remove,
        events,
      });
    }),
  );

/** What one turn's tool calls say about who wrote what. */
interface TurnWrites {
  /** The turn ran a tool whose writes are not derivable — shell, MCP. */
  readonly opaque: boolean;
  /** Paths the turn's declaring tools named, workspace-relative. */
  readonly declared: ReadonlySet<string>;
}

/**
 * The transcript's model record: the last `model_change` entry wins, exactly
 * as Pi replays it when rebuilding session context. Create always writes one,
 * so an absent record only means an empty or foreign transcript — resolution
 * then falls back to the default policy rather than failing a session that
 * could still run.
 */
const modelOf = (entries: readonly SessionTreeEntry[]): Models.ModelRef | undefined => {
  for (let index = entries.length - 1; index >= 0; index -= 1) {
    const entry = entries[index];
    if (entry?.type === "model_change") {
      return { providerId: entry.provider, modelId: entry.modelId };
    }
  }
  return undefined;
};

/**
 * Collects the attribution gate for one turn: the entries after the previous
 * snapshot up to and including this one.
 *
 * An absent index means the boundary entry is not in the transcript — `base`
 * never is — and widens the range to the corresponding end, which errs toward
 * claiming more rather than silently dropping a write.
 */
const turnToolWrites = (
  entries: readonly SessionTreeEntry[],
  fromIndex: number | undefined,
  toIndex: number | undefined,
): TurnWrites => {
  const start = fromIndex === undefined ? 0 : fromIndex + 1;
  const end = toIndex === undefined ? entries.length - 1 : toIndex;

  let opaque = false;
  const declared = new Set<string>();
  for (let index = start; index <= end; index += 1) {
    const entry = entries[index];
    if (entry === undefined || entry.type !== "message") continue;
    if (entry.message.role !== "assistant" || typeof entry.message.content === "string") continue;
    for (const block of entry.message.content) {
      if (block.type !== "toolCall") continue;
      const writes = Tools.writesOf(block.name, block.arguments);
      if (writes.kind === "opaque") opaque = true;
      if (writes.kind === "declared") {
        for (const path of writes.paths) declared.add(normalizePath(path));
      }
    }
  }
  return { opaque, declared };
};

/**
 * Applies the gate: a declaring-only turn claims exactly the paths it named,
 * an opaque turn claims the whole diff. Filtering an opaque turn would
 * silently hide real writes, which is the one failure mode this read must
 * never have.
 */
const gateTurnFiles = (
  files: readonly Git.FileChange[],
  writes: TurnWrites,
): readonly Git.FileChange[] => {
  if (writes.opaque) return files;
  return files.filter((file) => writes.declared.has(normalizePath(file.file)));
};

/** Aligns a tool-argument path with the workspace-relative form git reports. */
const normalizePath = (path: string): string => {
  let value = path;
  while (value.startsWith("./")) value = value.slice(2);
  return value;
};

/**
 * Normalizes a Pi value for JSON transport.
 *
 * Pi values can carry explicit `undefined` properties, which JSON cannot
 * represent, so the serializer rejects them. This round-trips each value
 * through JSON exactly once — the same normalization Pi's own JSONL persistence
 * applies — and changes nothing else.
 *
 * TODO(core-migration §6): hand-rolled normalization inside handlers, applied
 * per entry on every reload. Adopting Pi's protocol schemas moves this into the
 * codec at the boundary, where a value is parsed once and trusted after.
 */
const toWire = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

/**
 * Binds the session RPCs to {@link Service}.
 *
 * Handlers stay thin: decoding already happened at the RPC boundary, so they
 * only bind payloads to service methods and apply wire normalization. Provide
 * `layer(options)` to satisfy the `Service` requirement.
 *
 * @category layers
 */
export const rpcLayer = Rpcs.toLayer(
  Effect.gen(function* () {
    const session = yield* Service;
    return {
      "session.create": (payload) => session.create(payload),
      "session.prompt": (payload) => session.prompt(payload),
      "session.abort": (payload) => session.abort(payload),
      "session.steer": (payload) => session.steer(payload),
      "session.follow_up": (payload) => session.followUp(payload),
      "session.changes": (payload) => session.changes(payload),
      "session.set_workspace": (payload) => session.setWorkspace(payload),
      "session.revert": (payload) => session.revert(payload),
      "session.list": (payload) => session.list(payload),
      "session.get": (payload) => session.get(payload),
      "session.delete": (payload) => session.delete(payload),
      "session.reload": (payload) =>
        session
          .reload(payload)
          .pipe(Effect.map((state) => ({ ...state, entries: state.entries.map(toWire) }))),
      // Stream.unwrap folds the subscription Scope into the stream lifetime:
      // when the rpc call ends, the stream closes and the client detaches
      // without touching the run. The `live` head frame is prepended here
      // rather than inside the service, because in-process callers already get
      // that guarantee from the Effect resolving.
      "session.events": (payload) =>
        Stream.unwrap(
          session
            .events(payload)
            .pipe(
              Effect.map((stream) =>
                Stream.concat(
                  Stream.make({ type: "live" } as const),
                  stream.pipe(
                    Stream.map((event) => ({ type: "event", event: toWire(event) }) as const),
                  ),
                ),
              ),
            ),
        ),
    };
  }),
);

// Extensionless on purpose: consumers bundle this source (desktop keeps
// @honk/core in devDependencies so electron-vite bundles it), and consumer
// tsconfigs do not enable allowImportingTsExtensions.
// oxlint-disable-next-line import/no-self-import -- spec/effect.md self-reexport pattern; star imports are banned for consumers.
export * as Session from "./session";
