import type { Glyph } from "./icon";
import {
  IconArchive1,
  IconArrowLeft,
  IconArrowRight,
  IconArrowRightCircle,
  IconArrowRotateClockwise,
  IconArrowRotateCounterClockwise,
  IconArrowUp,
  IconBarsThree,
  IconBookSimple,
  IconBranch,
  IconBug,
  IconBrowserTabs,
  IconBrush,
  IconBubble2,
  IconBubbleCheck,
  IconBubbleQuestion,
  IconBuildingBlocks,
  IconCheckmark1,
  IconChanges,
  IconChevronDoubleLeft,
  IconChevronDoubleRight,
  IconChevronDownMedium,
  IconChevronLeftMedium,
  IconChevronRightMedium,
  IconChip,
  IconChatBubbles,
  IconCircleBanSign,
  IconCircleCheck,
  IconCircleDashed,
  IconCirclesThree,
  IconClawd,
  IconClipboard,
  IconCode,
  IconComputerUse,
  IconConsole,
  IconConsoleSimple,
  IconCrossMedium,
  IconCrossMediumDefault,
  IconCrossSmall,
  IconCupHot,
  IconDotGrid1x3Horizontal,
  IconExclamationCircle,
  IconExpand45,
  IconEyeOpen,
  IconFileBend,
  IconFileJpg,
  IconFilePdf,
  IconFilePng,
  IconFileText,
  IconFileZip,
  IconFiles,
  IconFilter2,
  IconFolder1,
  IconFolderAddRight,
  IconFolderOpen,
  IconGlobe,
  IconHandTouch,
  IconHomeRoofDoor,
  IconJavascript,
  IconJson,
  IconKimi,
  IconLayoutSidebar,
  IconMagnifyingGlass,
  IconMarkdown,
  IconMinimize45,
  IconMinusSmall,
  IconModelcontextprotocol,
  IconOngoing,
  IconOpenaiCodex,
  IconPencilLine,
  IconPin,
  IconPictureInPicture,
  IconPlanning,
  IconPlugin1,
  IconPlusSmall,
  IconProgress25,
  IconProgress50,
  IconProgress75,
  IconProgress100,
  IconPeopleIdCard2,
  IconPuzzle,
  IconSend,
  IconSettingsGear2,
  IconServer,
  IconShieldCode,
  IconSidebarSimpleRightWide,
  IconSleep,
  IconStepBack,
  IconStop,
  IconSummary,
  IconSun,
  IconSparklesSoft,
  IconTasks,
  IconToolbox,
  IconTodos,
  IconTrashCan,
  IconTypescript,
  IconUnpin,
  IconUserKey,
  IconWebhooks,
  IconWindowSquare,
  IconWindowSquarePlus,
  IconZai,
} from "central-icons";

// Navigation
export {
  IconArrowLeft,
  IconArrowRight,
  IconArrowRotateClockwise,
  IconChevronRightMedium,
  IconChevronDownMedium,
  IconChevronLeftMedium,
  IconChevronDoubleLeft,
  IconChevronDoubleRight,
  IconExpand45,
  IconMinimize45,
  IconStepBack,
};

// Files
export {
  IconFolder1,
  IconFolderOpen,
  IconFolderAddRight,
  IconFiles,
  IconFileBend,
  IconFileJpg,
  IconFilePdf,
  IconFilePng,
  IconFileText,
  IconFileZip,
  IconCode,
  IconJavascript,
  IconJson,
  IconMarkdown,
  IconTypescript,
};

// Content actions
export {
  IconPencilLine,
  IconTrashCan,
  IconClipboard,
  IconCheckmark1,
  IconArrowUp,
  IconArrowRotateCounterClockwise,
  IconPlusSmall,
  IconEyeOpen,
  IconPictureInPicture,
  IconMinusSmall,
  IconHandTouch,
  IconSend,
  IconStop,
};

// Triage
export { IconPin, IconUnpin, IconArchive1 };

// Close
export { IconCrossSmall, IconCrossMedium, IconCrossMediumDefault };

// Status
export {
  IconArrowRightCircle,
  IconCircleBanSign,
  IconCircleCheck,
  IconCircleDashed,
  IconExclamationCircle,
  IconOngoing,
  IconBubble2,
  IconBubbleCheck,
  IconBubbleQuestion,
  IconBug,
  IconChatBubbles,
  IconSleep,
  IconSun,
  IconProgress25,
  IconProgress50,
  IconProgress75,
  IconProgress100,
  IconTodos,
};

// Model providers
export { IconChip, IconClawd, IconKimi, IconOpenaiCodex, IconZai };

// Workspace
export {
  IconBarsThree,
  IconDotGrid1x3Horizontal,
  IconBrowserTabs,
  IconConsole,
  IconConsoleSimple,
  IconGlobe,
  IconChanges,
  IconHomeRoofDoor,
  IconSettingsGear2,
  IconBuildingBlocks,
  IconSparklesSoft,
  IconBranch,
  IconLayoutSidebar,
  IconSidebarSimpleRightWide,
  IconSummary,
  IconMagnifyingGlass,
  IconPlanning,
  IconTasks,
  IconFilter2,
  IconServer,
  IconComputerUse,
  IconWindowSquare,
  IconWindowSquarePlus,
  IconPlugin1,
  IconBookSimple,
  IconToolbox,
  IconCupHot,
  IconBrush,
  IconUserKey,
  IconPeopleIdCard2,
  IconPuzzle,
  IconShieldCode,
  IconModelcontextprotocol,
  IconWebhooks,
};

interface IconCatalogSection {
  readonly category: string;
  readonly glyphs: readonly (readonly [name: string, glyph: Glyph])[];
}

const ICON_CATALOG: readonly IconCatalogSection[] = [
  {
    category: "Navigation & disclosure",
    glyphs: [
      ["IconChevronRightMedium", IconChevronRightMedium],
      ["IconChevronDownMedium", IconChevronDownMedium],
      ["IconChevronLeftMedium", IconChevronLeftMedium],
      ["IconChevronDoubleLeft", IconChevronDoubleLeft],
      ["IconChevronDoubleRight", IconChevronDoubleRight],
      ["IconExpand45", IconExpand45],
      ["IconMinimize45", IconMinimize45],
      ["IconStepBack", IconStepBack],
    ],
  },
  {
    category: "Files & folders",
    glyphs: [
      ["IconFolder1", IconFolder1],
      ["IconFolderOpen", IconFolderOpen],
      ["IconFolderAddRight", IconFolderAddRight],
      ["IconFiles", IconFiles],
      ["IconFileBend", IconFileBend],
      ["IconFileJpg", IconFileJpg],
      ["IconFilePdf", IconFilePdf],
      ["IconFilePng", IconFilePng],
      ["IconFileText", IconFileText],
      ["IconFileZip", IconFileZip],
      ["IconCode", IconCode],
      ["IconJavascript", IconJavascript],
      ["IconJson", IconJson],
      ["IconMarkdown", IconMarkdown],
      ["IconTypescript", IconTypescript],
    ],
  },
  {
    category: "Content actions",
    glyphs: [
      ["IconPencilLine", IconPencilLine],
      ["IconTrashCan", IconTrashCan],
      ["IconClipboard", IconClipboard],
      ["IconCheckmark1", IconCheckmark1],
      ["IconArrowUp", IconArrowUp],
      ["IconPlusSmall", IconPlusSmall],
      ["IconEyeOpen", IconEyeOpen],
      ["IconPictureInPicture", IconPictureInPicture],
      ["IconMinusSmall", IconMinusSmall],
      ["IconSend", IconSend],
      ["IconStop", IconStop],
    ],
  },
  {
    category: "Triage & thread state",
    glyphs: [
      ["IconPin", IconPin],
      ["IconUnpin", IconUnpin],
      ["IconArchive1", IconArchive1],
    ],
  },
  {
    category: "Close & dismiss",
    glyphs: [
      ["IconCrossSmall", IconCrossSmall],
      ["IconCrossMedium", IconCrossMedium],
      ["IconCrossMediumDefault", IconCrossMediumDefault],
    ],
  },
  {
    category: "Status & feedback",
    glyphs: [
      ["IconArrowRightCircle", IconArrowRightCircle],
      ["IconCircleBanSign", IconCircleBanSign],
      ["IconCircleCheck", IconCircleCheck],
      ["IconCircleDashed", IconCircleDashed],
      ["IconCirclesThree", IconCirclesThree],
      ["IconExclamationCircle", IconExclamationCircle],
      ["IconOngoing", IconOngoing],
      ["IconBubble2", IconBubble2],
      ["IconBubbleCheck", IconBubbleCheck],
      ["IconBubbleQuestion", IconBubbleQuestion],
      ["IconBug", IconBug],
      ["IconChatBubbles", IconChatBubbles],
      ["IconSleep", IconSleep],
      ["IconSun", IconSun],
      ["IconProgress25", IconProgress25],
      ["IconProgress50", IconProgress50],
      ["IconProgress75", IconProgress75],
      ["IconProgress100", IconProgress100],
    ],
  },
  {
    category: "Model providers",
    glyphs: [
      ["IconChip", IconChip],
      ["IconClawd", IconClawd],
      ["IconKimi", IconKimi],
      ["IconOpenaiCodex", IconOpenaiCodex],
      ["IconZai", IconZai],
    ],
  },
  {
    category: "Workspace & chrome",
    glyphs: [
      ["IconBarsThree", IconBarsThree],
      ["IconDotGrid1x3Horizontal", IconDotGrid1x3Horizontal],
      ["IconBrowserTabs", IconBrowserTabs],
      ["IconConsole", IconConsole],
      ["IconConsoleSimple", IconConsoleSimple],
      ["IconGlobe", IconGlobe],
      ["IconChanges", IconChanges],
      ["IconHomeRoofDoor", IconHomeRoofDoor],
      ["IconSettingsGear2", IconSettingsGear2],
      ["IconBuildingBlocks", IconBuildingBlocks],
      ["IconSparklesSoft", IconSparklesSoft],
      ["IconBranch", IconBranch],
      ["IconLayoutSidebar", IconLayoutSidebar],
      ["IconSidebarSimpleRightWide", IconSidebarSimpleRightWide],
      ["IconSummary", IconSummary],
      ["IconPlanning", IconPlanning],
      ["IconTasks", IconTasks],
      ["IconMagnifyingGlass", IconMagnifyingGlass],
      ["IconFilter2", IconFilter2],
      ["IconServer", IconServer],
      ["IconComputerUse", IconComputerUse],
      ["IconWindowSquare", IconWindowSquare],
      ["IconWindowSquarePlus", IconWindowSquarePlus],
      ["IconPlugin1", IconPlugin1],
      ["IconBookSimple", IconBookSimple],
      ["IconToolbox", IconToolbox],
      ["IconCupHot", IconCupHot],
      ["IconBrush", IconBrush],
      ["IconUserKey", IconUserKey],
      ["IconPeopleIdCard2", IconPeopleIdCard2],
      ["IconPuzzle", IconPuzzle],
      ["IconShieldCode", IconShieldCode],
      ["IconModelcontextprotocol", IconModelcontextprotocol],
      ["IconWebhooks", IconWebhooks],
    ],
  },
];

export { ICON_CATALOG };
export type { IconCatalogSection };
