/**
 * Renderer-neutral Honk theme source.
 *
 * Light palette provenance is Cursor 3.11.25's bundled workbench core and
 * Cursor Light theme. Dark restores Honk's Cursor-derived workbench palette
 * from git, based on BioHazard786/cursor-theme-vscode's Cursor Dark.
 *
 * Values stay concrete so generated StyleX/CSS and React Native consume the
 * same contract. Run `pnpm --filter @honk/ui sync:tokens` after edits.
 */

const lightColors = {
  bgDeep: "#F3F3F3",
  bgChrome: "#F8F8F8",
  bgBase: "#FCFCFC",
  layer01: "#F3F3F3",
  layer02: "#EAEAEA",
  layer03: "#14141424",
  layer04: "#14141433",
  tabHover: "#14141414",
  bgInverse: "#141414",
  bgContrast: "#141414",
  textInverse: "#FCFCFC",
  textContrast: "#FCFCFC",
  textPrimary: "#141414",
  textMuted: "#141414BD",
  textFaint: "#1414145C",
  borderMuted: "#14141414",
  borderBase: "#1414141F",
  borderStrong: "#14141433",
  accent: "#2778C1",
  accentFill: "#2778C1",
  onAccent: "#FCFCFC",
  accentSubtle: "#2778C11F",
  control: "#14141424",
  controlHover: "#14141433",
  controlPress: "#1414144D",
  controlOpen: "#14141424",
  controlSelected: "#14141414",
  stateHover: "#14141414",
  statePress: "#14141424",
  scrim: "rgba(0,0,0,.32)",
  toastBg: "#1a1a1c",
  toastText: "#f5f5f7",
  toastMuted: "#a6a6ad",
  toastBorder: "rgba(255,255,255,.08)",
  toastSubtle: "rgba(255,255,255,.06)",
  toastActionText: "#0a0a0b",
  okFg: "#007041",
  warnFg: "#8B5700",
  errFg: "#BE1744",
  infoFg: "#176C74",
  okBg: "#00AF6624",
  warnBg: "#F6ECD9",
  errBg: "#FCE6EA",
  infoBg: "#E1EAEB",
  okBorder: "#00854C",
  warnBorder: "#A46700",
  errBorder: "#CE405B",
  infoBorder: "#3B7E84",
  presetLow: "#141414BD",
  presetMedium: "#007041",
  presetHigh: "#005293",
  presetUltra: "#654DC0",
  fg: "#141414",
  fgSecondary: "#141414BD",
  fgTertiary: "#14141499",
  fgRed: "#BE1744",
  iconTertiary: "#14141485",
  fileIconGray: "#84848A",
  fileIconRed: "#D52C36",
  fileIconVermilion: "#FF8C5B",
  fileIconOrange: "#D47628",
  fileIconYellow: "#D5A910",
  fileIconGreen: "#199F43",
  fileIconTeal: "#17A5AF",
  fileIconCyan: "#1CA1C7",
  fileIconBlue: "#1A85D4",
  fileIconIndigo: "#693ACF",
  fileIconPurple: "#A631BE",
  fileIconPink: "#D32A61",
  fileIconMauve: "#594C5B",
  strokeSecondary: "#1414141F",
  strokeTertiary: "#14141414",
  messageBubbleBg: "#F3F3F3",
  messageBubbleRing: "#14141414",
  diffAddition: "#007041",
  diffDeletion: "#BE1744",
  diffGutterAddition: "#007041",
  diffGutterDeletion: "#BE1744",
  diffGutterModification: "#A46700",
  diffLineAddition: "#00AF6624",
  diffLineDeletion: "#FF617B38",
  diffTextAddition: "#00B06838",
  diffTextDeletion: "#FF617B57",
  syntaxComment: "#14141499",
  syntaxKeyword: "#A30034",
  syntaxString: "#7565CC",
  syntaxNumber: "#92156A",
  syntaxFunction: "#CD4500",
  syntaxType: "#005293",
  syntaxProperty: "#654DC0",
  syntaxPunctuation: "#141414BD",
  terminalBlack: "#141414",
  terminalRed: "#BE1744",
  terminalGreen: "#007041",
  terminalYellow: "#8B5700",
  terminalBlue: "#0064B0",
  terminalMagenta: "#92156A",
  terminalCyan: "#176C74",
  terminalWhite: "#FCFCFC",
  terminalBrightBlack: "#141414BD",
  terminalBrightRed: "#CE405B",
  terminalBrightGreen: "#00854C",
  terminalBrightYellow: "#A46700",
  terminalBrightBlue: "#2778C1",
  terminalBrightMagenta: "#B54E90",
  terminalBrightCyan: "#3B7E84",
  terminalBrightWhite: "#FFFFFF",
  terminalSelection: "#14141424",
  terminalForeground: "#141414",
  // Project avatar palette (opencode OC-2 parity). Deterministic per-project
  // tint for the home Projects list; six fixed hues, bg + fg per hue.
  avatarPinkBg: "#feeef8",
  avatarMintBg: "#e1fbf4",
  avatarOrangeBg: "#fff1e7",
  avatarPurpleBg: "#f9f1fe",
  avatarCyanBg: "#e7f9fb",
  avatarLimeBg: "#eefadc",
  avatarPinkFg: "#cd1d8d",
  avatarMintFg: "#147d6f",
  avatarOrangeFg: "#ed5f00",
  avatarPurpleFg: "#8445bc",
  avatarCyanFg: "#0894b3",
  avatarLimeFg: "#5d770d",
} as const;

type ThemeColors = { readonly [Name in keyof typeof lightColors]: string };

const darkColors = {
  bgDeep: "#141414",
  bgChrome: "#141414",
  bgBase: "#181818",
  layer01: "#1C1C1C",
  layer02: "#252526",
  layer03: "#2A2A2A",
  layer04: "#404040",
  tabHover: "#2A2A2AB3",
  bgInverse: "#ffffff",
  bgContrast: "#626262",
  textInverse: "#141414",
  textContrast: "#F0F0F0",
  textPrimary: "#E4E4E4EB",
  textMuted: "#E4E4E48D",
  textFaint: "#E4E4E45E",
  borderMuted: "#E4E4E413",
  borderBase: "#E4E4E426",
  borderStrong: "#E4E4E44D",
  accent: "#599CE7",
  accentFill: "#599CE7",
  onAccent: "#191C22",
  accentSubtle: "#599CE726",
  control: "#1C1C1C",
  controlHover: "#262626",
  controlPress: "#404040",
  controlOpen: "#252526",
  controlSelected: "#E4E4E41E",
  stateHover: "#E4E4E411",
  statePress: "#E4E4E41E",
  scrim: "rgba(0,0,0,.55)",
  toastBg: "#1a1a1c",
  toastText: "#f5f5f7",
  toastMuted: "#a6a6ad",
  toastBorder: "rgba(255,255,255,.08)",
  toastSubtle: "rgba(255,255,255,.06)",
  toastActionText: "#0a0a0b",
  okFg: "#3FA266",
  warnFg: "#F1B467",
  errFg: "#FC6B83",
  infoFg: "#87C3FF",
  okBg: "#3FA26633",
  warnBg: "#D2943E33",
  errBg: "#B8004933",
  infoBg: "#599CE733",
  okBorder: "#70B489",
  warnBorder: "#D2943E",
  errBorder: "#FC6B83",
  infoBorder: "#81A1C1",
  presetLow: "#E4E4E48D",
  presetMedium: "#3FA266",
  presetHigh: "#87C3FF",
  presetUltra: "#AAA0FA",
  fg: "#E4E4E4EB",
  fgSecondary: "#E4E4E48D",
  fgTertiary: "#E4E4E45E",
  fgRed: "#FC6B83",
  iconTertiary: "#E4E4E45E",
  fileIconGray: "#ADADB1",
  fileIconRed: "#FF6762",
  fileIconVermilion: "#D5512F",
  fileIconOrange: "#FFA359",
  fileIconYellow: "#FFD452",
  fileIconGreen: "#5ECC71",
  fileIconTeal: "#64D1DB",
  fileIconCyan: "#68CDF2",
  fileIconBlue: "#69B1FF",
  fileIconIndigo: "#9D6AFB",
  fileIconPurple: "#D568EA",
  fileIconPink: "#FF678D",
  fileIconMauve: "#79697B",
  strokeSecondary: "#E4E4E41E",
  strokeTertiary: "#E4E4E413",
  messageBubbleBg: "#1C1C1C",
  messageBubbleRing: "#E4E4E41E",
  diffAddition: "#3FA266",
  diffDeletion: "#FC6B83",
  diffGutterAddition: "#3FA266",
  diffGutterDeletion: "#E34671",
  diffGutterModification: "#D2943E",
  diffLineAddition: "#3FA26633",
  diffLineDeletion: "#B8004933",
  diffTextAddition: "#3FA26622",
  diffTextDeletion: "#B8004922",
  syntaxComment: "#E4E4E45E",
  syntaxKeyword: "#82D2CE",
  syntaxString: "#E394DC",
  syntaxNumber: "#EBC88D",
  syntaxFunction: "#EFB080",
  syntaxType: "#87C3FF",
  syntaxProperty: "#AAA0FA",
  syntaxPunctuation: "#D6D6DD",
  terminalBlack: "#242424",
  terminalRed: "#FC6B83",
  terminalGreen: "#3FA266",
  terminalYellow: "#D2943E",
  terminalBlue: "#81A1C1",
  terminalMagenta: "#B48EAD",
  terminalCyan: "#88C0D0",
  terminalWhite: "#F0F0F0",
  terminalBrightBlack: "#F0F0F099",
  terminalBrightRed: "#FC6B83",
  terminalBrightGreen: "#70B489",
  terminalBrightYellow: "#F1B467",
  terminalBrightBlue: "#87A6C4",
  terminalBrightMagenta: "#B48EAD",
  terminalBrightCyan: "#88C0D0",
  terminalBrightWhite: "#FFFFFF",
  terminalSelection: "#F0F0F01E",
  terminalForeground: "#F0F0F0",
  avatarPinkBg: "#501b3f",
  avatarMintBg: "#033a34",
  avatarOrangeBg: "#5f2a06",
  avatarPurpleBg: "#432155",
  avatarCyanBg: "#0f3058",
  avatarLimeBg: "#2b3711",
  avatarPinkFg: "#e34ba9",
  avatarMintFg: "#95f3d9",
  avatarOrangeFg: "#ff802b",
  avatarPurpleFg: "#9d5bd2",
  avatarCyanFg: "#369eff",
  avatarLimeFg: "#c4f042",
} as const satisfies ThemeColors;

type ColorProvenance = {
  readonly [Name in keyof ThemeColors]: {
    readonly light: string;
    readonly dark: string;
  };
};

const source = (light: string, dark: string) => ({ light, dark });

/** The upstream ramp or explicit Honk derivation behind every semantic color. */
export const colorProvenance = {
  bgDeep: source("Cursor 3.11.25 core.sidebar", "Honk git: base chrome / Cursor sidebar"),
  bgChrome: source("Cursor 3.11.25 core.chrome", "Cursor core.chrome"),
  bgBase: source(
    "Cursor 3.11.25 core.editor / panel.background",
    "Honk git: base editor / Cursor editor",
  ),
  layer01: source("Cursor Light editorWidget.background", "Cursor input.background"),
  layer02: source("Cursor Light editor.lineHighlightBackground", "Honk git: elevated surface"),
  layer03: source("Cursor semantic bg-secondary (base at 14%)", "Cursor hover surface"),
  layer04: source("Cursor semantic bg-primary (base at 20%)", "Cursor selection surface"),
  tabHover: source("Cursor Light tab.hoverBackground", "Cursor tab.unfocusedHoverBackground"),
  bgInverse: source("Cursor 3.11.25 core.base", "Honk inverse"),
  bgContrast: source("Cursor 3.11.25 core.base", "Cursor button.secondaryBackground"),
  textInverse: source("Cursor 3.11.25 core.editor", "Cursor chrome background"),
  textContrast: source("Cursor 3.11.25 core.actionLabel", "Honk git: base focus"),
  textPrimary: source("Cursor 3.11.25 semantic text-primary", "Cursor foreground"),
  textMuted: source("Cursor semantic text-secondary (base at 74%)", "Cursor secondary foreground"),
  textFaint: source(
    "Cursor semantic text-quaternary (base at 36%)",
    "Cursor placeholder foreground",
  ),
  borderMuted: source("Cursor semantic stroke-tertiary (base at 8%)", "Cursor border at 8%"),
  borderBase: source(
    "Cursor semantic stroke-secondary (base at 12%)",
    "Cursor focus border at 15%",
  ),
  borderStrong: source("Cursor semantic stroke-primary (base at 20%)", "Cursor foreground at 30%"),
  accent: source("Cursor 3.11.25 core.accent", "Honk git: Cursor-derived accent"),
  accentFill: source("Cursor 3.11.25 core.accent", "Honk git: Cursor-derived accent"),
  onAccent: source("Cursor 3.11.25 core.actionLabel", "Cursor button.foreground"),
  accentSubtle: source(
    "Cursor semantic bg-accent-tertiary (accent at 12%)",
    "Honk Cursor accent at 15%",
  ),
  control: source("Cursor Light button.secondaryBackground", "Cursor input.background"),
  controlHover: source(
    "Cursor Light button.secondaryHoverBackground",
    "Cursor editor.lineHighlightBackground",
  ),
  controlPress: source("Cursor Light base at 30%", "Cursor editor.selectionBackground"),
  controlOpen: source("Cursor Light button.secondaryBackground", "Honk git: elevated surface"),
  controlSelected: source("Cursor Light list.activeSelectionBackground", "Cursor active selection"),
  stateHover: source("Cursor Light list.hoverBackground", "Cursor list.hoverBackground"),
  statePress: source("Cursor Light list.focusBackground", "Cursor list.activeSelectionBackground"),
  scrim: source("Honk dialog scrim", "Honk dark scrim"),
  toastBg: source("Honk toast neutral", "Honk toast neutral"),
  toastText: source("Honk toast neutral", "Honk toast neutral"),
  toastMuted: source("Honk toast neutral", "Honk toast neutral"),
  toastBorder: source("Honk toast neutral", "Honk toast neutral"),
  toastSubtle: source("Honk toast neutral", "Honk toast neutral"),
  toastActionText: source("Honk toast neutral", "Honk toast neutral"),
  okFg: source("Cursor 3.11.25 core.success", "Honk git: Cursor diff green"),
  warnFg: source("Cursor Light inputValidation.warningForeground", "Honk git: Cursor warning"),
  errFg: source("Cursor 3.11.25 core.danger", "Honk git: Cursor error"),
  infoFg: source("Cursor Light inputValidation.infoForeground", "Honk git: Cursor type blue"),
  okBg: source("Cursor 3.11.25 diffAddedLineBackground", "Cursor inserted line background"),
  warnBg: source("Cursor Light inputValidation.warningBackground", "Cursor warning at 20%"),
  errBg: source("Cursor Light inputValidation.errorBackground", "Cursor removed line background"),
  infoBg: source("Cursor Light inputValidation.infoBackground", "Honk Cursor accent at 20%"),
  okBorder: source("Cursor 3.11.25 terminalAnsiBrightGreen", "Cursor bright green"),
  warnBorder: source("Cursor Light inputValidation.warningBorder", "Cursor terminal yellow"),
  errBorder: source("Cursor Light inputValidation.errorBorder", "Cursor error"),
  infoBorder: source("Cursor Light inputValidation.infoBorder", "Cursor terminal blue"),
  presetLow: source("Cursor semantic text-secondary", "Cursor secondary foreground"),
  presetMedium: source("Cursor core.success", "Cursor diff green"),
  presetHigh: source("Cursor Light type foreground", "Cursor type blue"),
  presetUltra: source("Cursor Light property foreground", "Cursor property violet"),
  fg: source("Cursor semantic text-primary", "Cursor foreground"),
  fgSecondary: source(
    "Cursor semantic text-secondary (base at 74%)",
    "Cursor secondary foreground",
  ),
  fgTertiary: source(
    "Cursor semantic text-tertiary (base at 60%)",
    "Cursor placeholder foreground",
  ),
  fgRed: source("Cursor core.danger", "Cursor error"),
  iconTertiary: source(
    "Cursor semantic icon-tertiary (base at 52%)",
    "Cursor placeholder foreground",
  ),
  fileIconGray: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconRed: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconVermilion: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconOrange: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconYellow: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconGreen: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconTeal: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconCyan: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconBlue: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconIndigo: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconPurple: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconPink: source("Pierre Application File Icons", "Pierre Application File Icons"),
  fileIconMauve: source("Pierre Application File Icons", "Pierre Application File Icons"),
  strokeSecondary: source(
    "Cursor semantic stroke-secondary (base at 12%)",
    "Cursor active selection",
  ),
  strokeTertiary: source("Cursor semantic stroke-tertiary (base at 8%)", "Cursor border"),
  messageBubbleBg: source("Cursor Light editorWidget.background", "Cursor input.background"),
  messageBubbleRing: source("Cursor semantic stroke-tertiary", "Cursor active selection"),
  diffAddition: source("Cursor 3.11.25 core.added", "Honk git: Cursor diff green"),
  diffDeletion: source("Cursor 3.11.25 core.removed", "Honk git: Cursor diff red"),
  diffGutterAddition: source(
    "Cursor Light editorGutter.addedBackground",
    "Cursor Dark editorGutter.addedBackground",
  ),
  diffGutterDeletion: source(
    "Cursor Light editorGutter.deletedBackground",
    "Cursor Dark editorGutter.deletedBackground",
  ),
  diffGutterModification: source(
    "Cursor Light editorGutter.modifiedBackground",
    "Cursor Dark editorGutter.modifiedBackground",
  ),
  diffLineAddition: source(
    "Cursor Light diffEditor.insertedLineBackground",
    "Cursor Dark diffEditor.insertedLineBackground",
  ),
  diffLineDeletion: source(
    "Cursor Light diffEditor.removedLineBackground",
    "Cursor Dark diffEditor.removedLineBackground",
  ),
  diffTextAddition: source(
    "Cursor Light diffEditor.insertedTextBackground",
    "Cursor Dark diffEditor.insertedTextBackground",
  ),
  diffTextDeletion: source(
    "Cursor Light diffEditor.removedTextBackground",
    "Cursor Dark diffEditor.removedTextBackground",
  ),
  syntaxComment: source("Cursor Light token Comments", "Honk dark diff theme comment"),
  syntaxKeyword: source("Cursor Light token Keywords", "Honk dark diff theme keyword"),
  syntaxString: source("Cursor Light token Strings", "Honk dark diff theme string"),
  syntaxNumber: source("Cursor Light token Integers", "Honk dark diff theme number"),
  syntaxFunction: source(
    "Cursor Light token Function Names",
    "Honk dark diff theme function",
  ),
  syntaxType: source("Cursor Light semantic type", "Honk dark diff theme type"),
  syntaxProperty: source("Cursor Light token Properties", "Honk dark diff theme property"),
  syntaxPunctuation: source(
    "Cursor Light token Punctuation",
    "Honk dark diff theme punctuation",
  ),
  terminalBlack: source("Cursor 3.11.25 terminalAnsiBlack", "Honk git terminal ANSI black"),
  terminalRed: source("errFg", "Honk git terminal ANSI red"),
  terminalGreen: source("okFg", "Honk git terminal ANSI green"),
  terminalYellow: source("warnFg", "Honk git terminal ANSI yellow"),
  terminalBlue: source("accent", "Honk git terminal ANSI blue"),
  terminalMagenta: source("presetUltra", "Honk git terminal ANSI magenta"),
  terminalCyan: source("infoFg", "Honk git terminal ANSI cyan"),
  terminalWhite: source("Cursor 3.11.25 terminalAnsiWhite", "Cursor 3.11.25 terminalAnsiWhite"),
  terminalBrightBlack: source(
    "Cursor 3.11.25 terminalAnsiBrightBlack",
    "Cursor 3.11.25 terminalAnsiBrightBlack",
  ),
  terminalBrightRed: source("Cursor 3.11.25 terminalAnsiBrightRed", "Honk git terminal bright red"),
  terminalBrightGreen: source(
    "Cursor 3.11.25 terminalAnsiBrightGreen",
    "Honk git terminal bright green",
  ),
  terminalBrightYellow: source(
    "Cursor 3.11.25 terminalAnsiBrightYellow",
    "Honk git terminal bright yellow",
  ),
  terminalBrightBlue: source(
    "Cursor 3.11.25 terminalAnsiBrightBlue",
    "Honk git terminal bright blue",
  ),
  terminalBrightMagenta: source(
    "Cursor 3.11.25 terminalAnsiBrightMagenta",
    "Honk git terminal bright magenta",
  ),
  terminalBrightCyan: source(
    "Cursor 3.11.25 terminalAnsiBrightCyan",
    "Honk git terminal bright cyan",
  ),
  terminalBrightWhite: source(
    "Cursor 3.11.25 terminalAnsiBrightWhite",
    "Cursor 3.11.25 terminalAnsiBrightWhite",
  ),
  terminalSelection: source(
    "Cursor Light terminal.selectionBackground",
    "Cursor Dark terminal.selectionBackground",
  ),
  terminalForeground: source("Cursor Light terminal.foreground", "Cursor Dark terminal.foreground"),
  avatarPinkBg: source("opencode OC-2 avatar pink surface", "opencode OC-2 avatar pink surface"),
  avatarMintBg: source("opencode OC-2 avatar mint surface", "opencode OC-2 avatar mint surface"),
  avatarOrangeBg: source(
    "opencode OC-2 avatar orange surface",
    "opencode OC-2 avatar orange surface",
  ),
  avatarPurpleBg: source(
    "opencode OC-2 avatar purple surface",
    "opencode OC-2 avatar purple surface",
  ),
  avatarCyanBg: source("opencode OC-2 avatar cyan surface", "opencode OC-2 avatar cyan surface"),
  avatarLimeBg: source("opencode OC-2 avatar lime surface", "opencode OC-2 avatar lime surface"),
  avatarPinkFg: source("opencode OC-2 avatar pink text", "opencode OC-2 avatar pink text"),
  avatarMintFg: source("opencode OC-2 avatar mint text", "opencode OC-2 avatar mint text"),
  avatarOrangeFg: source("opencode OC-2 avatar orange text", "opencode OC-2 avatar orange text"),
  avatarPurpleFg: source("opencode OC-2 avatar purple text", "opencode OC-2 avatar purple text"),
  avatarCyanFg: source("opencode OC-2 avatar cyan text", "opencode OC-2 avatar cyan text"),
  avatarLimeFg: source("opencode OC-2 avatar lime text", "opencode OC-2 avatar lime text"),
} as const satisfies ColorProvenance;

const webMetrics = {
  radius: {
    panel: 10,
    window: 12,
    // Menu-class popups (menu, combobox, picker popovers): concentric with the 6px row
    // radius plus the 4px edge gutter. Cursor's ui-menu ships 8px with the same row
    // geometry; 10px keeps the rings true.
    menu: 10,
    control: 6,
    field: 8,
    avatar: 4,
    pill: 999,
    bubble: 12,
  },
  space: {
    gutter: 8,
    panelPad: 12,
    controlPadX: 10,
  },
  control: {
    heightSm: 24,
    heightMd: 28,
    heightLg: 32,
    paddingSm: 8,
    paddingMd: 10,
    paddingLg: 12,
    gap: 6,
    multilineMinHeight: 80,
    // Shared edge gutter for menu-class popups (Cursor ui-menu section padding): every
    // dropdown insets its rounded row highlight this distance from the popup wall.
    menuPad: 4,
    pickerMinWidth: 200,
    pickerMaxWidth: 320,
    pickerRichMinHeight: 44,
    borderWidth: 1,
    focusRingWidth: 1,
    focusRingOffset: 2,
    disabledOpacity: 0.4,
  },
  font: {
    familyUi: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    familyMono: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    familyRounded:
      'ui-rounded, "SF Pro Rounded", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    sizeBody: 13,
    sizeDetail: 12,
    sizeCaption: 11,
    sizeMicro: 10,
    sizeBodyLg: 14,
    leadingBodyLg: 21,
    sizeCode: 12,
    // Cursor 3.12.6 AnySphere UI tokens: xs 11/14, sm 12/16, base 13/18, lg 14/20.
    textCaption: 11,
    textDetail: 12,
    textBody: 13,
    textTitle: 14,
    textHeading: 16,
    leadingCaption: 14,
    leadingDetail: 16,
    leadingBody: 18,
    leadingTitle: 20,
    leadingHeading: 21,
    leadingCode: 18,
    letterSpacingCaption: 0.07,
    letterSpacingDetail: 0,
    letterSpacingBody: -0.08,
    letterSpacingBodyLg: -0.15,
    weightRegular: 400,
    weightSemibold: 600,
    // Text-rendering keywords. The appearance store pins these vars to "auto" on <html>
    // when the user selects native/system rasterization.
    smoothing: "antialiased",
    smoothingMoz: "grayscale",
  },
  icon: {
    sizeXs: 12,
    sizeSm: 14,
    sizeMd: 16,
    sizeLg: 18,
    sizeXl: 20,
  },
  conversation: {
    inset: 11,
    rowMinHeight: 24,
    rowGap: 4,
    stepGap: 6,
  },
  // Copied from old-main packages/app/src/styles/shell.css + honkkit sidebar.tsx.
  sidebar: {
    itemHeight: 28,
    itemGap: 4,
    rowPaddingInline: 6,
    rowPaddingBlock: 4,
    sectionGap: 8,
    gutterInline: 8,
    labelSize: 13,
    labelLeading: 20,
    subtitleSize: 11,
    subtitleLeading: 14,
    iconSlot: 16,
  },
} as const;

const nativeMetrics = {
  radius: {
    panel: 10,
    control: 8,
    field: 10,
    avatar: 6,
    pill: 999,
    bubble: 12,
  },
  space: {
    screenGutter: 14,
    panelPad: 12,
    sectionGap: 20,
    rowGap: 10,
    contentGap: 8,
    compactGap: 4,
  },
  field: {
    minHeightMd: 44,
    minHeightLg: 48,
    paddingInlineMd: 12,
    paddingInlineLg: 14,
    paddingBlockMd: 9,
    paddingBlockLg: 12,
    paddingBlockAndroidMd: 7,
    paddingBlockAndroidLg: 10,
    accessoryGap: 8,
    labelGap: 6,
    errorGap: 4,
    borderWidth: 1,
    focusBorderWidth: 2,
  },
  button: {
    height: 40,
    compactHeight: 36,
    paddingInline: 12,
    compactPaddingInline: 10,
    borderWidth: 1,
  },
  font: {
    bodySize: 15,
    bodyLeading: 21,
    detailSize: 13,
    detailLeading: 18,
    captionSize: 12,
    captionLeading: 16,
    titleSize: 19,
    titleLeading: 24,
    weightRegular: "400",
    weightMedium: "500",
    weightSemibold: "600",
  },
  interaction: {
    touchTarget: 44,
    disabledOpacity: 0.5,
    pressedOpacity: 0.8,
  },
  feed: {
    avatarSize: 36,
    avatarGap: 10,
    rowPaddingBlock: 12,
  },
  composer: {
    attachmentSize: 64,
    maxHeight: 132,
  },
} as const;

export const honkTheme = {
  colors: {
    light: lightColors,
    dark: darkColors,
  },
  web: webMetrics,
  native: nativeMetrics,
} as const;

export type ThemeMode = keyof typeof honkTheme.colors;
export type NativeTheme = {
  readonly mode: ThemeMode;
  readonly colors: ThemeColors;
  readonly metrics: typeof nativeMetrics;
};

export const resolveNativeTheme = (mode: ThemeMode): NativeTheme => ({
  mode,
  colors: honkTheme.colors[mode],
  metrics: honkTheme.native,
});
