#!/usr/bin/env node

// Vendors Pi's remote-session protocol schemas verbatim.
//
// Pi does not publish @earendil-works/pi-protocol to npm yet, so this script
// follows the t3code pattern for the codex app-server: pin an upstream ref,
// fetch the schema source at that exact commit, and commit it unchanged.
// Byte-identical vendoring means zero translation drift; the schemas stay
// Pi-owned. Bumping the pin means editing UPSTREAM_REF and rerunning
// `pnpm generate`; upstream drift then shows up as a reviewable diff. When Pi
// publishes the package, this whole package dissolves into a dependency swap.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const UPSTREAM_REF = "f0deb8dd8e9611e89b5bc4145ca92c03ae6ed4ee";
const RAW_BASE = `https://raw.githubusercontent.com/earendil-works/pi/${UPSTREAM_REF}`;

const fetchText = async (url: string): Promise<string> => {
  const response = await fetch(url, {
    headers: { "user-agent": "honk-pi-protocol-vendoring" },
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return response.text();
};

const packageJson = JSON.parse(await fetchText(`${RAW_BASE}/packages/protocol/package.json`)) as {
  version: string;
};
const source = await fetchText(`${RAW_BASE}/packages/protocol/src/schemas.ts`);

const generatedDir = path.join(import.meta.dirname, "..", "src", "_generated");
await mkdir(generatedDir, { recursive: true });
// schemas.ts stays byte-identical to upstream; provenance lives in meta.gen.ts.
await writeFile(path.join(generatedDir, "schemas.ts"), source);
await writeFile(
  path.join(generatedDir, "meta.gen.ts"),
  [
    "// Generated by @honk/pi-protocol scripts/generate.ts. Do not edit.",
    `export const UPSTREAM_REF = "${UPSTREAM_REF}";`,
    `export const UPSTREAM_VERSION = "${packageJson.version}";`,
    "",
  ].join("\n"),
);

console.log(`Vendored pi-protocol ${packageJson.version} schemas at ${UPSTREAM_REF}`);
